<?php
    $v_params = $this->getParams();
    
    $vo = new ChamadosVo();
    
    $mensagem = "";
    if (array_key_exists('mensagem', $v_params)) {
        $mensagem = $v_params['mensagem'];
    }
    
    $situacoes = array();
    if (array_key_exists('situacoes', $v_params)) {
        $situacoes = $v_params['situacoes'];
    }
    
    $usuarios = array();
    if (array_key_exists('usuarios', $v_params)) {
        $usuarios = $v_params['usuarios'];
    }
    
    $atendentes = array();
    if (array_key_exists('atendentes', $v_params)) {
        $atendentes = $v_params['atendentes'];
    }
    
    $empresas = array();
    if (array_key_exists('empresas', $v_params)) {
        $empresas = $v_params['empresas'];
    }
    
    $categorias = array();
    if (array_key_exists('categorias', $v_params)) {
        $categorias = $v_params['categorias'];
    }
    
    $tiposAmbientes = array();
    if (array_key_exists('tiposAmbientes', $v_params)) {
        $tiposAmbientes = $v_params['tiposAmbientes'];
    }
    
    $tiposProdutos = array();
    if (array_key_exists('tiposProdutos', $v_params)) {
        $tiposProdutos = $v_params['tiposProdutos'];
    }
    
    $modulos = array();
    if (array_key_exists('modulos', $v_params)) {
        $modulos = $v_params['modulos'];
    }
    
    $prioridades = array();
    if (array_key_exists('prioridades', $v_params)) {
        $prioridades = $v_params['prioridades'];
    }
    
    $dataIni = date("d/m/Y", strtotime("-30 days"));
    $dataFim = date("d/m/Y");
    
    $usuarioCodigo = $_SESSION['usuarioCodigo'];
    $usuarioNome = $_SESSION['usuarioNome'];
    
    if ($_SESSION['perfilCliente'] == 1) {
        $exibeUsuarioAberto = true;
        $exibeRequisitante = false;
        $exibeCategoria = false;
        $exibeTipoAmbiente = false;
        $exibeTipoProduto = false;
        $exibeModulo = false;
        $exibePrioridade = false;
        $exibeAssunto = false;
        $exibeAcoesEmbaixo = false;
    } else {
        $exibeUsuarioAberto = true;
        $exibeRequisitante = true;
        $exibeCategoria = true;
        $exibeTipoAmbiente = true;
        $exibeTipoProduto = true;
        $exibeModulo = true;
        $exibePrioridade = true;
        $exibeAssunto = true;
        $exibeAcoesEmbaixo = true;
    }
    
    if (Functions::isEmpty($_SESSION['empresaCodigo'])) {
        $exibeEmpresaAberta = true;
        $empresaCodigo = "";
        $empresaDescricao = "";
    } else {
        $exibeEmpresaAberta = false;
        $empresaCodigo = $_SESSION['empresaCodigo'];
        $empresaDescricao = $_SESSION['empresaDescricao'];
    }
?>

<?php include 'pageopen.php' ?>

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script>
    $(document).ready(function() {
        $(".datepicker").datepicker({dateFormat: 'dd/mm/yy'});
    });
    function loadClientesDeUmaEmpresa(empresaCodigo, exibeUsuarioAberto, usuarioCodigo) {
        var ajax;
        if (window.XMLHttpRequest)
            ajax = new XMLHttpRequest();
        else
            ajax = new ActiveXObject("Microsoft.XMLHTTP");
        
        ajax.onreadystatechange = function() {
            if (ajax.readyState == 4 && ajax.status == 200) {
                document.getElementById("divUsuario").innerHTML = ajax.responseText;
            }
        }
        ajax.open("POST", "?controle=Usuarios&acao=ajaxLoadClientesDeUmaEmpresa", true);
        ajax.setRequestHeader("Content-type","application/x-www-form-urlencoded");
        ajax.send("empresaCodigo=" + empresaCodigo + "&exibeUsuarioAberto=" + exibeUsuarioAberto + "&usuarioCodigo=" + usuarioCodigo);
    }
</script>

<div class="container">
    
    <div class="page-header">
        <h3>Chamados<small> / Filtros para Consulta</small></h3>
    </div>
    
    <?php
    if (!empty($mensagem)) {
        if (substr($mensagem,0,1) == "N") {
            echo '<div class="alert alert-danger"><strong>ERRO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
        if (substr($mensagem,0,1) == "S") {
            echo '<div class="alert alert-success"><strong>SUCESSO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
    }
    ?>
    
    <form class="form-horizontal" role="form" method="post" onsubmit="return verifica();">
        
        <button type="button" class="btn btn-default" onclick="javascript:incluir();">
            <span class="glyphicon glyphicon-file"></span>&nbsp;&nbsp;Novo
        </button>
        
        <button type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-search"></span>&nbsp;&nbsp;Consultar
        </button>
        
        <p><br /></p>
        
        <input type='hidden' name='controle' value='chamados'>
        <input type='hidden' name='acao' value='listar'>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="id">Código:</label>
            <div class="col-sm-3">
                <input type="text" class="form-control" id="id" name="id" value="">
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="dataIni">Data Abertura (de):</label>
            <div class="col-sm-3">
                <input type="text" class="form-control datepicker" id="dataIni" name="dataIni" value="<?php echo $dataIni?>" />
            </div>
            <label class="control-label col-sm-2" for="dataFim">Data Abertura (até):</label>
            <div class="col-sm-3">
                <input type="text" class="form-control datepicker" id="dataFim" name="dataFim" value="<?php echo $dataFim?>" />
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="atendente">Analista:</label>
            <div class="col-sm-3">
                <select class="form-control" id="atendente" name="atendente">
                    <option value="">Selecione</option>
                    <?php
                    foreach($atendentes as $atendente) {
                        echo '<option value="' . $atendente->getId() . '">' . $atendente->getNome() . '</option>';
                    }
                    ?>
                </select>
            </div>
            <label class="control-label col-sm-2" for="situacao">Situação:</label>
            <div class="col-sm-3">
                <select class="form-control" id="situacao" name="situacao">
                    <option value="">Selecione</option>
                    <?php
                    foreach($situacoes as $situacao) {
                        echo '<option value="' . $situacao->getId() . '">' . $situacao->getDescricao() . '</option>';
                    }
                    ?>
                </select>
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="empresa">Empresa:</label>
            <div class="col-sm-3">
                <?php 
                if ($exibeEmpresaAberta) {
                    echo '<select class="form-control" id="empresa" name="empresa" onchange="loadClientesDeUmaEmpresa(this.value' . ',' . ($exibeUsuarioAberto ? 1 : 0) . ',' . $usuarioCodigo . ')">';
                    echo '<option value="">Selecione</option>';
                    foreach($empresas as $empresa) {
                        echo '<option value="' . $empresa->getId() . '">' . $empresa->getDescricao() . '</option>';
                    }
                    echo '</select>';
                } else {
                    echo '<input type="hidden" name="empresa" value="' . $empresaCodigo . '" />';
                    echo '<input type="text" class="form-control" id="empresa" name="empresa" value="' . $empresaDescricao . '" disabled="disabled" />';
                }
                ?>
            </div>
            
            <div id="divUsuario">

            </div>
        </div>
        
        <?php if (($exibeRequisitante) || ($exibeCategoria)) { ?>
        <div class="form-group">
            <?php if ($exibeRequisitante) { ?>
            <label class="control-label col-sm-2" for="requisitante">Requisitante:</label>
            <div class="col-sm-3">
                <select class="form-control" id="requisitante" name="requisitante">
                    <option value="">Selecione</option>
                    <?php
                    foreach($usuarios as $usuario) {
                        echo '<option value="' . $usuario->getId() . '">' . $usuario->getNome() . '</option>';
                    }
                    ?>
                </select>
            </div>
            <?php } ?>
            <?php if ($exibeCategoria) { ?>
            <label class="control-label col-sm-2" for="categoria">Categoria:</label>
            <div class="col-sm-3">
                <select class="form-control" id="categoria" name="categoria">
                    <option value="">Selecione</option>
                    <?php
                    foreach($categorias as $categoria) {
                        echo '<option value="' . $categoria->getId() . '">' . $categoria->getDescricao() . '</option>';
                    }
                    ?>
                </select>
            </div>
            <?php } ?>
        </div>
        <?php } ?>
        
        <?php if (($exibeTipoAmbiente) || ($exibeTipoProduto)) { ?>
        <div class="form-group">
            <?php if ($exibeTipoAmbiente) { ?>
            <label class="control-label col-sm-2" for="tipoAmbiente">Tipo de Ambiente:</label>
            <div class="col-sm-3">
                <select class="form-control" id="tipoAmbiente" name="tipoAmbiente">
                    <option value="">Selecione</option>
                    <?php
                    foreach($tiposAmbientes as $tipoAmbiente) {
                        echo '<option value="' . $tipoAmbiente->getId() . '">' . $tipoAmbiente->getDescricao() . '</option>';
                    }
                    ?>
                </select>
            </div>
            <?php } ?>
            <?php if ($exibeTipoProduto) { ?>
            <label class="control-label col-sm-2" for="tipoProduto">Tipo de Produto:</label>
            <div class="col-sm-3">
                <select class="form-control" id="tipoProduto" name="tipoProduto">
                    <option value="">Selecione</option>
                    <?php
                    foreach($tiposProdutos as $tipoProduto) {
                        echo '<option value="' . $tipoProduto->getId() . '">' . $tipoProduto->getDescricao() . '</option>';
                    }
                    ?>
                </select>
            </div>
            <?php } ?>
        </div>
        <?php } ?>
        
        <?php if (($exibeModulo) || ($exibePrioridade)) { ?>
        <div class="form-group">
            <?php if ($exibeModulo) { ?>
            <label class="control-label col-sm-2" for="modulo">Módulo:</label>
            <div class="col-sm-3">
                <select class="form-control" id="modulo" name="modulo">
                    <option value="">Selecione</option>
                    <?php
                    foreach($modulos as $modulo) {
                        echo '<option value="' . $modulo->getId() . '">' . $modulo->getDescricao() . '</option>';
                    }
                    ?>
                </select>
            </div>
            <?php } ?>
            <?php if ($exibePrioridade) { ?>
            <label class="control-label col-sm-2" for="prioridade">Prioridade:</label>
            <div class="col-sm-3">
                <select class="form-control" id="prioridade" name="prioridade">
                    <option value="">Selecione</option>
                    <?php
                    foreach($prioridades as $prioridade) {
                        echo '<option value="' . $prioridade->getId() . '">' . $prioridade->getDescricao() . '</option>';
                    }
                    ?>
                </select>
            </div>
            <?php } ?>
        </div>
        <?php } ?>
        
        <?php if ($exibeAssunto) { ?>
        <div class="form-group">
            <label class="control-label col-sm-2" for="assunto">Assunto:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="assunto" name="assunto" value="">
            </div>
        </div>
        <?php } ?>
        
        <?php if ($exibeAcoesEmbaixo) { ?>
        <div class="form-group">
            <label class="control-label col-sm-2" for="observacao">Ações:</label>
            <div class="col-sm-10">
                <button type="button" class="btn btn-default" onclick="javascript:incluir();">
                    <span class="glyphicon glyphicon-file"></span>&nbsp;&nbsp;Novo
                </button>
                
                <button type="submit" class="btn btn-default">
                    <span class="glyphicon glyphicon-search"></span>&nbsp;&nbsp;Consultar
                </button>
            </div>
        </div>
        <?php } ?>
        
    </form>
    
</div>

<script>
    function incluir() {
        postViaJS('', {controle: 'Chamados', acao: 'cadastrar'}, "post", "_blank");
    }
    function verifica() {
        var markupStr = $('#summernote').summernote('code');
        document.getElementById('observacao').value = markupStr;
        return true;
    }
</script>

<?php
if (Functions::isEmpty($_SESSION['empresaCodigo'])) {
    echo '<script>loadClientesDeUmaEmpresa("", ' . ($exibeUsuarioAberto ? 1 : 0) . ',' . $usuarioCodigo . ');</script>';
} else {
    echo '<script>loadClientesDeUmaEmpresa(' . $empresaCodigo . ', ' . ($exibeUsuarioAberto ? 1 : 0) . ',' . $usuarioCodigo . ');</script>';
}
?>

<?php include 'pageclose.php';			
