<?php
    $v_params = $this->getParams();
    
    $mensagem = "";
    if (array_key_exists('mensagem', $v_params)) {
        $mensagem = $v_params['mensagem'];
    }
    
    $descricao = "";
    if (array_key_exists('descricao', $v_params)) {
        $descricao = $v_params['descricao'];
    }
    
    $situacao = "";
    if (array_key_exists('situacao', $v_params)) {
        $situacao = $v_params['situacao'];
    }
    
    $registros = array();
    if (array_key_exists('registros', $v_params)) {
        $registros = $v_params['registros'];
    }
?>

<?php include 'pageopen.php' ?>

<div class="container">
    
    <div class="page-header">
        <h3>Categorias<small> / Tela de Listagem</small></h3>
    </div>
    
    <?php
    if (!Functions::isEmpty($mensagem)) {
        if (substr($mensagem,0,1) == "N") {
            echo '<div class="alert alert-danger"><strong>ERRO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
        if (substr($mensagem,0,1) == "S") {
            echo '<div class="alert alert-success"><strong>SUCESSO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
    }
    ?>
    
    <form name="filtros" role="form" method="post">
        <div class="row">
            <input type='hidden' name='controle' value='Categorias'>
            <input type='hidden' name='acao' value='listar'>
            <div class="col-xs-1" style="width:95px">
                <button type="button" class="btn btn-default" style="width:90px" onclick="javascript:incluir();">
                    <span class="glyphicon glyphicon-file"></span>&nbsp;&nbsp;Novo
                </button>
            </div>
            <div class="col-xs-1" style="width:205px">
                <input type="text" class="form-control" id="descricao" name="descricao" style="width:200px" value="<?php echo $descricao ?>">
            </div>
            <div class="col-xs-1" style="width:95px">
                <select class="form-control" id="situacao" name="situacao" style="width:90px">
                    <option value="1">Ativos</option>
                    <option value="9">Inativos</option>
                </select>
            </div>
            <div class="col-xs-1">
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span> Buscar</button>
                <script>document.filtros.situacao.value = <?php echo $situacao ?></script>
            </div>
        </div>
    </form>
    
    <p><br /></p>
    
    <div class="table-responsive">
        <table class="table table-striped">

            <thead>
                <tr>
                    <th class="col-xs-8">Descrição</th>
                    <th class="col-xs-4">Situação</th>
                </tr>
            </thead>

            <tbody>
                <?php foreach($registros AS $registro) { ?>
                <tr>
                    <td><a href="javascript:;" onclick="javascript:editar(<?php echo $registro->getId()?>);"><?php echo $registro->getDescricao()?></a></td>
                    <td><?php echo $registro->getSituacaoExtenso()?></td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
    
</div>

<script type="text/javascript">
    function incluir() {
        postViaJS('', {controle: 'Categorias', acao: 'cadastrar'});
    }
    function editar(codigo) {
        postViaJS('', {controle: 'Categorias', acao: 'cadastrar', id: codigo});
    }
    function excluir(codigo) {
        postViaJS('', {controle: 'Categorias', acao: 'excluir', id: codigo});
    }
</script>

<?php include 'pageclose.php';