<?php
    $v_params = $this->getParams();
    
    $mensagem = "";
    if (array_key_exists('mensagem', $v_params)) {
        $mensagem = $v_params['mensagem'];
    }
    
    $descricao = "";
    if (array_key_exists('descricao', $v_params)) {
        $descricao = $v_params['descricao'];
    }
    
    $situacao = "";
    if (array_key_exists('situacao', $v_params)) {
        $situacao = $v_params['situacao'];
    }
    
    $registros = array();
    if (array_key_exists('registros', $v_params)) {
        $registros = $v_params['registros'];
    }
?>

<?php include 'pageopen.php' ?>

<div class="container">
    
    <div class="page-header">
        <h3>Usuários<small> / Tela de Listagem</small></h3>
    </div>
    
    <?php
    if (!Functions::isEmpty($mensagem)) {
        if (substr($mensagem,0,1) == "N") {
            echo '<div class="alert alert-danger"><strong>ERRO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
        if (substr($mensagem,0,1) == "S") {
            echo '<div class="alert alert-success"><strong>SUCESSO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
    }
    ?>
    
    <form name="filtros" role="form" method="post">
        <div class="row">
            <input type='hidden' name='controle' value='Usuarios'>
            <input type='hidden' name='acao' value='listar'>
            <?php if ($_SESSION['perfilAdministrador'] == 1) { ?>
            <div class="col-xs-1" style="width:95px">
                <button type="button" class="btn btn-default" style="width:90px" onclick="javascript:incluir();">
                    <span class="glyphicon glyphicon-file"></span>&nbsp;&nbsp;Novo
                </button>
            </div>
            <?php } ?>
            <div class="col-xs-1" style="width:205px">
                <input type="text" class="form-control" id="descricao" name="descricao" style="width:200px" value="<?php echo $descricao ?>">
            </div>
            <div class="col-xs-1" style="width:95px">
                <select class="form-control" id="situacao" name="situacao" style="width:90px">
                    <option value="1">Ativos</option>
                    <option value="9">Inativos</option>
                </select>
            </div>
            <div class="col-xs-1">
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span> Buscar</button>
                <script>document.filtros.situacao.value = <?php echo $situacao ?></script>
            </div>
        </div>
    </form>
    
    <p><br /></p>
    
    <div class="table-responsive">
        <table class="table table-striped">
        
            <thead>
                <tr>
                    <th class="col-xs-3">Nome</th>
                    <th class="col-xs-3">Empresa</th>
                    <th class="col-xs-3">Contato</th>
                    <th class="col-xs-2">Perfil</th>
                    <th class="col-sm-1">Situação</th>
                </tr>
            </thead>
            
            
            <tbody>
                <?php foreach($registros AS $registro) { ?>
                <tr>
                    <td><a href="javascript:;" onclick="javascript:editar(<?php echo $registro->getId()?>);"><?php echo $registro->getNome()?></a></td>
                    <td><?php echo $registro->getEmpresa()->getDescricao()?></td>
                    <td>
                        <p>
                            <span class="glyphicon glyphicon-envelope"></span>&nbsp;&nbsp;<?php echo $registro->getEmail()?><br />
                            <span class="glyphicon glyphicon-phone-alt"></span>&nbsp;&nbsp;<?php echo $registro->getFoneComercial()?><br />
                            <span class="glyphicon glyphicon-phone"></span>&nbsp;&nbsp;<?php echo $registro->getFoneCelular()?><br />
                        </p>
                    </td>
                    <td><?php echo $registro->getPerfil()->getDescricao()?></td>
                    <td><?php echo $registro->getSituacaoExtenso()?></td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
    
</div>

<script type="text/javascript">
    function incluir() {
        postViaJS('', {controle: 'Usuarios', acao: 'cadastrar'});
    }
    function editar(tipoSistemaCodigo) {
        postViaJS('', {controle: 'Usuarios', acao: 'cadastrar', id: tipoSistemaCodigo});
    }
    function excluir(tipoSistemaCodigo) {
        postViaJS('', {controle: 'Usuarios', acao: 'excluir', id: tipoSistemaCodigo});
    }
</script>

<?php include 'pageclose.php';