<?php
    $v_params = $this->getParams();
    
    $mensagem = "";
    if (array_key_exists('mensagem', $v_params)) {
        $mensagem = $v_params['mensagem'];
    }
    
    $registros = array();
    if (array_key_exists('registros', $v_params)) {
        $registros = $v_params['registros'];
    }
?>

<?php include 'pageopen.php' ?>

<div class="container">
    
    <div class="page-header">
        <h3>Atividades<small> / Tela de Listagem</small></h3>
    </div>
    
    <?php
    if (!Functions::isEmpty($mensagem)) {
        if (substr($mensagem,0,1) == "N") {
            echo '<div class="alert alert-danger"><strong>ERRO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
        if (substr($mensagem,0,1) == "S") {
            echo '<div class="alert alert-success"><strong>SUCESSO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
    }
    ?>
    
    <button type="button" class="btn btn-default" onclick="javascript:voltar();">
        <span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Voltar
    </button>
    
    <button type="button" class="btn btn-default" onclick="javascript:incluir();">
        <span class="glyphicon glyphicon-file"></span>&nbsp;&nbsp;Novo
    </button>
    
    <p><br /></p>
    
    <table class="table table-striped">
        
        <thead>
	    <tr>
                <th class="col-sm-1">Código</th>
                <th class="col-sm-1">Abertura</th>
                <th class="col-sm-1">Situação</th>
                <th class="col-sm-2">Analista</th>
                <th class="col-sm-2">Empresa</th>
                <th class="col-sm-2">Tipo de Atividade</th>
                <th class="col-sm-3" nowrap>Descrição</th>
            </tr>
        </thead>
	
        <tbody>
            <?php foreach($registros AS $registro) { ?>
            <tr>
                <td><?php echo '<a href="javascript:editar(' . $registro->getId() . ');">' . $registro->getId() . '</a>'?></td>
                <td><?php echo $registro->getData()?></td>
                <td><?php echo $registro->getSituacao()->getDescricao()?></td>
                <td><?php echo $registro->getUsuario()->getNome()?></td>
                <td><?php echo $registro->getEmpresa()->getDescricao()?></td>
                <td><?php echo $registro->getTipoAtividade()->getDescricao()?></td>
                <td><?php echo $registro->getObservacao()?></td>
            </tr>
            <?php } ?>
        </tbody>
        
    </table>
    
</div>

<script type="text/javascript">
    function voltar() {
        postViaJS('', {controle: 'Atividades', acao: 'filtrar'});
    }
    function incluir() {
        postViaJS('', {controle: 'Atividades', acao: 'cadastrar'}, "post", "_blank");
    }
    function editar(atividadeCodigo) {
        postViaJS('', {controle: 'Atividades', acao: 'cadastrar', id: atividadeCodigo}, "post", "_blank");
    }
</script>

<?php include 'pageclose.php';