<?php
    $v_params = $this->getParams();
    
    $mensagem = "";
    if (array_key_exists('mensagem', $v_params)) {
        $mensagem = $v_params['mensagem'];
    }
    
    $registros = array();
    if (array_key_exists('registros', $v_params)) {
        $registros = $v_params['registros'];
    }
?>

<?php include 'pageopen.php' ?>

<div class="container">
    
    <div class="page-header">
        <h3>Usuários<small> / Tela de Listagem</small></h3>
    </div>
    
    <?php
    if (!Functions::isEmpty($mensagem)) {
        if (substr($mensagem,0,1) == "N") {
            echo '<div class="alert alert-danger"><strong>ERRO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
        if (substr($mensagem,0,1) == "S") {
            echo '<div class="alert alert-success"><strong>SUCESSO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
    }
    ?>
    
    <?php if ($_SESSION['perfilAdministrador'] == 1) { ?>
    <button type="button" class="btn btn-default" onclick="javascript:incluir();">
        <span class="glyphicon glyphicon-file"></span>&nbsp;&nbsp;Novo
    </button>
    <?php } ?>
    
    <p><br /></p>
    
    <table class="table table-striped">
        <thead>
            <tr>
                <th class="col-xs-1">#</th>
                <th class="col-xs-3">Nome</th>
                <th class="col-xs-2">Perfil</th>
                <th class="col-xs-2">Empresa</th>
                <th class="col-xs-3">Contato</th>
                <th class="col-xs-1">Situação</th>
            </tr>
        </thead>
	    
        <tbody>
            <?php foreach($registros AS $usuario) { ?>
            <tr>
                <td><a href="javascript:editar(<?php echo $usuario->getId()?>);"><?php echo $usuario->getId()?></a></td>
                <td><?php echo $usuario->getNome()?></td>
                <td><?php echo $usuario->getPerfil()->getDescricao()?></td>
                <td><?php echo $usuario->getEmpresa()->getDescricao()?></td>
                <td>
                    <p>
                        <span class="glyphicon glyphicon-envelope"></span>&nbsp;&nbsp;<?php echo $usuario->getEmail()?><br />
                        <span class="glyphicon glyphicon-phone-alt"></span>&nbsp;&nbsp;<?php echo $usuario->getFoneComercial()?><br />
                        <span class="glyphicon glyphicon-phone"></span>&nbsp;&nbsp;<?php echo $usuario->getFoneCelular()?><br />
                    </p>
                </td>
                <td><?php echo $usuario->getSituacaoExtenso()?></td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
    
</div>

<script type="text/javascript">
    function incluir() {
        postViaJS('', {controle: 'Usuarios', acao: 'cadastrar'});
    }
    function editar(tipoSistemaCodigo) {
        postViaJS('', {controle: 'Usuarios', acao: 'cadastrar', id: tipoSistemaCodigo});
    }
    function excluir(tipoSistemaCodigo) {
        postViaJS('', {controle: 'Usuarios', acao: 'excluir', id: tipoSistemaCodigo});
    }
</script>

<?php include 'pageclose.php';