<?php
    $v_params = $this->getParams();
    
    $mensagem = "";
    if (array_key_exists('mensagem', $v_params)) {
        $mensagem = $v_params['mensagem'];
    }
?>

<!DOCTYPE html>
<html lang="en">
    
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link rel="shortcut icon" href="template/images/favicon.ico">
        
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>BasisIT</title>
        
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        
        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        
        <!-- Latest compiled JavaScript -->
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        
        <link href="template/css/template.css" rel="stylesheet">
        
        <script type="text/javascript" src="template/js/default.js"></script>
        
        <script type="text/javascript">
            function inicializar() {
                document.forms[0].email.focus();
            }
        </script>
    </head>
    
<body onload="inicializar()">
    
    <div id="header">
        <img src="template/images/bg-header.jpg" alt="" width="100%" />
        <nav class="navbar navbar-default navbar-static-top" role="navigation"></nav>
    </div>
    
    <div class="container">
        
        <div class="page-header">
            <h3>Login<small> / Informe suas credenciais de acesso</small></h3>
        </div>
        
        <?php
        if (!Functions::isEmpty($mensagem)) {
            if (substr($mensagem,0,1) == "N") {
                echo '<div class="alert alert-danger"><strong>ERRO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
            }
            if (substr($mensagem,0,1) == "S") {
                echo '<div class="alert alert-success"><strong>SUCESSO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
            }
        }
        ?>
        
        <form class="form-horizontal" role="form" method="post">
            
            <p><br /></p>
            
            <input type='hidden' name='controle' value='Index'>
            <input type='hidden' name='acao' value='login'>
            
            <div class="form-group">
                <label class="control-label col-sm-2" for="email">E-mail:</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="email" name="email" value="">
                </div>
            </div>
            
            <div class="form-group">
                <label class="control-label col-sm-2" for="senha">Senha:</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" id="senha" name="senha" value="">
                </div>
            </div>
            
            <div class="form-group">
                <label class="control-label col-sm-2" for="acessar"></label>
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-default">
                        <span class="glyphicon glyphicon-share-alt"></span>&nbsp;Acessar
                    </button>
                </div>
            </div>
            
        </form>
        
    </div>
    
<?php include 'pageclose.php';