<?php
    $v_params = $this->getParams();
    
    $mensagem = "";
    if (array_key_exists('mensagem', $v_params)) {
        $mensagem = $v_params['mensagem'];
    }
    
    $apontamento = new ApontamentosVo();
    if (array_key_exists('apontamento', $v_params)) {
        $apontamento = $v_params['apontamento'];
    }
    
    $usuarios = array();
    if (array_key_exists('usuarios', $v_params)) {
        $usuarios = $v_params['usuarios'];
    }
    
    $atividade = "";
    if (array_key_exists('atividade', $v_params)) {
        $atividade = $v_params['atividade'];
    }
    
    $chamado = "";
    if (array_key_exists('chamado', $v_params)) {
        $chamado = $v_params['chamado'];
    }
    
    if ($_SESSION['perfilAdministrador'] == 1) {
        $exibeUsuarioAberto = true;
        $usuarioCodigo = "";
        $usuarioNome = "";
    } else {
        $exibeUsuarioAberto = false;
        $usuarioCodigo = $_SESSION['usuarioCodigo'];
        $usuarioNome = $_SESSION['usuarioNome'];
    }
?>

<?php include 'pageopen.php' ?>

<link href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>

<script>
    $(document).ready(function() {
        $(".datepicker").datepicker({dateFormat: 'dd/mm/yy'});
    });
</script>

<div class="container">
    
    <div class="page-header">
        <h3>Apontamentos<small> / Tela de Cadastro</small></h3>
    </div>
    
    <?php
    if (!empty($mensagem)) {
        if (substr($mensagem,0,1) == "N") {
            echo '<div class="alert alert-danger"><strong>ERRO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
        if (substr($mensagem,0,1) == "S") {
            echo '<div class="alert alert-success"><strong>SUCESSO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
    }
    ?>
    
    <form class="form-horizontal" role="form" method="post" name="form">
        
        <?php
        if (!Functions::isEmpty($atividade)) {
            echo '<button type="button" class="btn btn-default" onclick="javascript:voltarAtividade(' . $atividade . ');">';
            echo '<span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Voltar';
            echo '</button>';
        }
        if (!Functions::isEmpty($chamado)) {
            echo '<button type="button" class="btn btn-default" onclick="javascript:voltarChamado(' . $chamado . ');">';
            echo '<span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Voltar';
            echo '</button>';
        }
        ?>
        
        <button type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;&nbsp;Salvar 
        </button>
        
        <p><br /></p>
        
        <input type='hidden' name='controle' value='Apontamentos'>
        <input type='hidden' name='acao' value='salvarCadastrar'>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="id">Código:</label>
            <div class="col-sm-10">
                <input type="hidden" id="id" name="id" value="<?php echo $apontamento->getId() ?>">
                <input type="text" class="form-control" id="id" name="id" placeholder="Será gerado automaticamente pelo sistema" value="<?php echo $apontamento->getId()?>" disabled="disabled">
            </div>
        </div>
        
        <div class="form-group">
        <?php
        if (!Functions::isEmpty($atividade)) {
            echo '<label class="control-label col-sm-2" for="atividade">Atividade:</label>';
            echo '<div class="col-sm-10">';
            echo '<input type="hidden" id="atividade" name="atividade" value="' . $atividade . '">';
            echo '<input type="text" class="form-control" id="atividade" name="atividade" placeholder="Será gerado automaticamente pelo sistema" value="' . $atividade . '" disabled="disabled">';
            echo '</div>';
        }
        if (!Functions::isEmpty($chamado)) {
            echo '<label class="control-label col-sm-2" for="chamado">Chamado:</label>';
            echo '<div class="col-sm-10">';
            echo '<input type="hidden" id="chamado" name="chamado" value="' . $chamado . '">';
            echo '<input type="text" class="form-control" id="chamado" name="chamado" placeholder="Será gerado automaticamente pelo sistema" value="' . $chamado . '" disabled="disabled">';
            echo '</div>';
        }
        ?>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="usuario">Usuário:</label>
            <div class="col-sm-10">
                <?php 
                if ($exibeUsuarioAberto) {
                    echo '<select class="form-control" id="usuario" name="usuario">';
                    echo '<option value="">Selecione</option>';
                    foreach($usuarios as $usuario) {
                        if ($apontamento->getUsuario() != "" && $usuario->getId() == $apontamento->getUsuario()->getId()) {
                            echo '<option value="' . $usuario->getId() . '" selected>' . $usuario->getNome() . '</option>';
                        } else {
                            echo '<option value="' . $usuario->getId() . '">' . $usuario->getNome() . '</option>';
                        }
                    }
                    echo '</select>';
                } else {
                    echo '<input type="hidden" name="usuario" value="' . $usuarioCodigo . '" />';
                    echo '<input type="text" class="form-control" id="usuario" name="usuario" value="' . $usuarioNome . '" disabled="disabled" />';
                }
                ?>
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="dataInicio">Data/Hora Início:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="dataInicio" name="dataInicio" placeholder="Informe a data no formato DD/MM/AAAA HH:MM:SS" value="<?php echo $apontamento->getDataInicio()?>">
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="dataFim">Data/Hora Final:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="dataFim" name="dataFim" placeholder="Informe a data no formato DD/MM/AAAA HH:MM:SS" value="<?php echo $apontamento->getDataFim()?>">
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="observacao">Observação:</label>
            <div class="col-sm-10">
                <textarea class="form-control" rows="5" id="observacao" name="observacao" placeholder="Espaço para informações adicionais do apontamento"><?php echo $apontamento->getObservacao()?></textarea>
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="apontado">Valor Apontado:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="apontado" name="apontado" placeholder="Será calculado no momento da gravação" value="<?php echo $apontamento->getApontado()?>" disabled="disabled">
            </div>
        </div>
        
        <?php if (Functions::isEmpty($apontamento->getApontado())) {?>
            <div class="form-group">
                <label class="control-label col-sm-2" for="avaliacao">Tipo Avaliação:</label>
                <div class="col-sm-10">
                    <input type="hidden" id="avaliacao" name="avaliacao" value="<?php echo $apontamento->getAvaliacao()?>" />
                    <input type="text" class="form-control" id="avaliacao" name="avaliacao" placeholder="Apenas será possível editar esse campo depois que o campo Valor Apontado estiver preenchido" value="" disabled="disabled">
                </div>
            </div>
            
            <div class="form-group">
                <label class="control-label col-sm-2" for="faturado">Valor Faturado:</label>
                <div class="col-sm-10">
                    <input type="hidden" id="faturado" name="faturado" value="<?php echo $apontamento->getFaturado()?>" />
                    <input type="text" class="form-control" id="faturado" name="faturado" placeholder="Apenas será possível editar esse campo depois que o campo Valor Apontado estiver preenchido" value="" disabled="disabled">
                </div>
            </div>
        <?php } else { ?>
            <div class="form-group">
                <label class="control-label col-sm-2" for="avaliacao">Tipo de Avaliação:</label>
                <div class="col-sm-10">
                    <select class="form-control" id="avaliacao" name="avaliacao" onchange="verificaHorasFaturar()">
                        <option value=""  <?php echo $apontamento->getAvaliacao() == ""  ? "selected" : "" ?>>Selecione</option>
                        <option value="9" <?php echo $apontamento->getAvaliacao() == "9" ? "selected" : "" ?>>Não Avaliado</option>
                        <option value="1" <?php echo $apontamento->getAvaliacao() == "1" ? "selected" : "" ?>>Faturado Integral</option>
                        <option value="2" <?php echo $apontamento->getAvaliacao() == "2" ? "selected" : "" ?>>Faturado Parcial</option>
                        <option value="3" <?php echo $apontamento->getAvaliacao() == "3" ? "selected" : "" ?>>Não Faturado</option>
                    </select>
                </div>
            </div>
            
            <div class="form-group">
                <label class="control-label col-sm-2" for="faturado">Valor Faturado:</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="faturado" name="faturado" value="<?php echo $apontamento->getFaturado()?>">
                </div>
            </div>
        <?php } ?>
        
    </form>
    
</div>

<script type="text/javascript">
    function voltarAtividade(atividadeCodigo) {
        postViaJS('', {controle: 'Atividades', acao: 'cadastrar', id: atividadeCodigo});
    }
    function voltarChamado(chamadoCodigo) {
        postViaJS('', {controle: 'Chamados', acao: 'cadastrar', id: chamadoCodigo});
    }
    function verificaHorasFaturar() {
        if (document.form.elements['avaliacao'].value == "" ) {
            document.form.elements['faturado'].value = "00:00:00";
      	}
      	if (document.form.elements['avaliacao'].value == "0") {
            document.form.elements['faturado'].value = "00:00:00";
      	}
      	if (document.form.elements['avaliacao'].value == "1") {
            document.form.elements['faturado'].value = document.form.elements['apontado'].value;
      	}
      	if (document.form.elements['avaliacao'].value == "2") {
            document.form.elements['faturado'].value = document.form.elements['apontado'].value;
      	}
        document.form.elements['faturado'].focus();
    }
</script>

<?php include 'pageclose.php';