<?php
    $v_params = $this->getParams();
    
    $mensagem = "";
    if (array_key_exists('mensagem', $v_params)) {
        $mensagem = $v_params['mensagem'];
    }
    
    $usuario = new UsuariosVo();
    if (array_key_exists('usuario', $v_params)) {
        $usuario = $v_params['usuario'];
    }
    
    $perfis = array();
    if (array_key_exists('perfis', $v_params)) {
        $perfis = $v_params['perfis'];
    }
    
    $empresas = array();
    if (array_key_exists('empresas', $v_params)) {
        $empresas = $v_params['empresas'];
    }
?>

<?php include 'pageopen.php'; ?>

<div class="container">
    
    <div class="page-header">
        <h3>Usuários<small> / Tela de Cadastro</small></h3>
    </div>
    
    <?php
    if (!empty($mensagem)) {
        if (substr($mensagem,0,1) == "N") {
            echo '<div class="alert alert-danger"><strong>ERRO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
        if (substr($mensagem,0,1) == "S") {
            echo '<div class="alert alert-success"><strong>SUCESSO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
    }
    ?>
    
    <form class="form-horizontal" role="form" method="post" onsubmit="return verifica();">
        
        <button type="button" class="btn btn-default" onclick="javascript:voltar();">
            <span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Voltar
        </button>
        
        <button type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;&nbsp;Salvar 
        </button>
        
        <p><br /></p>
        
        <input type='hidden' name='controle' value='Usuarios'>
        <input type='hidden' name='acao' value='salvarCadastrar'>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="id">Código:</label>
            <div class="col-sm-1">
                <input type="hidden" id="id" name="id" value="<?php echo $usuario->getId() ?>">
                <input type="text" class="form-control" id="id" name="id" value="<?php echo $usuario->getId()?>" disabled="disabled">
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="nome">Nome:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="nome" name="nome" value="<?php echo $usuario->getNome()?>">
            </div>
            <label class="control-label col-sm-1" for="perfil">Perfil:</label>
            <div class="col-sm-3">
                <select class="form-control" id="perfil" name="perfil">
                    <option value="">Selecione</option>
                    <?php
                    foreach($perfis as $perfil) {
                        if ($usuario->getPerfil() != "" && $perfil->getId() == $usuario->getPerfil()->getId()) {
                            echo '<option value="' . $perfil->getId() . '" selected>' . $perfil->getDescricao() . '</option>';
                        } else {
                            echo '<option value="' . $perfil->getId() . '">' . $perfil->getDescricao() . '</option>';
                        }
                    }
                    ?>
                </select>
                <?php if ($_SESSION['perfilAdministrador'] == 0) { ?>
                <script>
                    document.forms[0].perfil.disabled = true;
                </script>
                <?php } ?>
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="setor">Setor:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="setor" name="setor" value="<?php echo $usuario->getSetor()?>">
            </div>
            <label class="control-label col-sm-1" for="perfil">Empresa:</label>
            <div class="col-sm-3">
                <select class="form-control" id="empresa" name="empresa">
                    <option value="">Selecione</option>
                    <?php
                    foreach($empresas as $empresa) {
                        if ($usuario->getEmpresa() != "" && $empresa->getId() == $usuario->getEmpresa()->getId()) {
                            echo '<option value="' . $empresa->getId() . '" selected>' . $empresa->getDescricao() . '</option>';
                        } else { 
                            echo '<option value="' . $empresa->getId() . '">' . $empresa->getDescricao() . '</option>';
                        }
                    }
                    ?>
                </select>
            </div>
            <?php if ($_SESSION['perfilAdministrador'] == 0) { ?>
            <script>
                document.forms[0].empresa.disabled = true;
            </script>
            <?php } ?>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="email">E-mail:</label>
            <div class="col-sm-4">
                <div class="input-group">   
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-envelope"></span> 
                    </div>
                    <input type="text" class="form-control" id="email" name="email" value="<?php echo $usuario->getEmail()?>">
                </div>
            </div>
            <label class="control-label col-sm-1" for="email">Telefone:</label>
            <div class="col-sm-3">
                <div class="input-group">   
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-phone-alt"></span> 
                    </div>
                    <input type="text" class="form-control" id="foneComercial" name="foneComercial" value="<?php echo $usuario->getFoneComercial()?>">
                </div>
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="senha">Senha:</label>
            <div class="col-sm-2">
                <input type="password" class="form-control" id="senha" name="senha" value="">
            </div>
            <label class="control-label col-sm-3" for="email">Celular:</label>
            <div class="col-sm-3">
                <div class="input-group">   
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-phone"></span> 
                    </div>
                    <input type="text" class="form-control" id="foneCelular" name="foneCelular" value="<?php echo $usuario->getFoneCelular()?>">
                </div>
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="situacao">Situação:</label>
            <div class="col-sm-4">
                <label class="radio-inline"><input type="radio" name="situacao" value="1" <?php echo ( $registro->getSituacao() == 1 ) ? 'checked="checked"' : '' ?> >Ativo</label>
                <label class="radio-inline"><input type="radio" name="situacao" value="9" <?php echo ( $registro->getSituacao() == 9 ) ? 'checked="checked"' : '' ?> >Inativo</label>
            </div>
        </div>
        
        <!-- include summernote css/js-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.1/summernote.css" rel="stylesheet">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.1/summernote.js"></script>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="observacao">Observação:</label>
            <div class="col-sm-8">
                <input type="hidden" id="observacao" name="observacao" value="">
                <div id="summernote" name="summernote"><p><?php echo $usuario->getObservacao()?></p></div>
            </div>
            <script>
                $(document).ready(function() {
                    $('#summernote').summernote({
                        height: 200
                    });
                });
            </script>
        </div>
        
    </form>
    
</div>

<script type="text/javascript">
    function voltar() {
        postViaJS('', {controle: 'Usuarios', acao: 'listar'});
    }
    function verifica() {
        var markupStr = $('#summernote').summernote('code');
        document.getElementById('observacao').value = markupStr;
        return true;
    }
</script>

<?php include 'pageclose.php';