<?php
    $v_params = $this->getParams();
    
    $mensagem = "";
    if (array_key_exists('mensagem', $v_params)) {
        $mensagem = $v_params['mensagem'];
    }
    
    $usuario = new UsuariosVo();
    if (array_key_exists('usuario', $v_params)) {
        $usuario = $v_params['usuario'];
    }
    
    $perfis = array();
    if (array_key_exists('perfis', $v_params)) {
        $perfis = $v_params['perfis'];
    }
    
    $empresas = array();
    if (array_key_exists('empresas', $v_params)) {
        $empresas = $v_params['empresas'];
    }
?>

<?php include 'pageopen.php' ?>

<div class="container">
    
    <div class="page-header">
        <h3>Usuários<small> / Tela de Cadastro</small></h3>
    </div>
    
    <?php
    if (!empty($mensagem)) {
        if (substr($mensagem,0,1) == "N") {
            echo '<div class="alert alert-danger"><strong>ERRO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
        if (substr($mensagem,0,1) == "S") {
            echo '<div class="alert alert-success"><strong>SUCESSO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
    }
    ?>
    
    <form class="form-horizontal" role="form" method="post">
        
        <button type="button" class="btn btn-default" onclick="javascript:voltar();">
            <span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Voltar
        </button>
        
        <button type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;&nbsp;Salvar 
        </button>
        
        <p><br /></p>
        
        <input type='hidden' name='controle' value='Usuarios'>
        <input type='hidden' name='acao' value='salvarCadastrar'>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="id">Código:</label>
            <div class="col-sm-10">
                <input type="hidden" id="id" name="id" value="<?php echo $usuario->getId() ?>">
                <input type="text" class="form-control" id="id" name="id" placeholder="Será gerado automaticamente pelo sistema" value="<?php echo $usuario->getId()?>" disabled="disabled">
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="nome">Nome:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="nome" name="nome" placeholder="Informe o nome do usuário" value="<?php echo $usuario->getNome()?>">
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="email">E-mail:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="email" name="email" placeholder="Informe o e-mail do usuário" value="<?php echo $usuario->getEmail()?>">
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="senha">Senha:</label>
            <div class="col-sm-10">
                <input type="password" class="form-control" id="senha" name="senha" placeholder="Informe a senha do usuário" value="<?php echo $usuario->getSenha()?>">
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="perfil">Perfil:</label>
            <div class="col-sm-10">
                <select class="form-control" id="perfil" name="perfil">
                    <option value="">Selecione</option>
                    <?php
                    foreach($perfis as $perfil) {
                        if ($usuario->getPerfil() != "" && $perfil->getId() == $usuario->getPerfil()->getId()) {
                            echo '<option value="' . $perfil->getId() . '" selected>' . $perfil->getDescricao() . '</option>';
                        } else {
                            echo '<option value="' . $perfil->getId() . '">' . $perfil->getDescricao() . '</option>';
                        }
                    }
                    ?>
                </select>
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="perfil">Empresa:</label>
            <div class="col-sm-10">
                <select class="form-control" id="empresa" name="empresa">
                    <option value="">Selecione</option>
                    <?php
                    foreach($empresas as $empresa) {
                        if ($usuario->getEmpresa() != "" && $empresa->getId() == $usuario->getEmpresa()->getId()) {
                            echo '<option value="' . $empresa->getId() . '" selected>' . $empresa->getDescricao() . '</option>';
                        } else { 
                            echo '<option value="' . $empresa->getId() . '">' . $empresa->getDescricao() . '</option>';
                        }
                    }
                    ?>
                </select>
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="setor">Setor:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="setor" name="setor" placeholder="Informe o setor do usuário" value="<?php echo $usuario->getSetor()?>">
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="email">Fone Comercial:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="foneComercial" name="foneComercial" placeholder="Informe o fone comercial do usuário" value="<?php echo $usuario->getFoneComercial()?>">
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="email">Fone Celular:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="foneCelular" name="foneCelular" placeholder="Informe o fone celular do usuário" value="<?php echo $usuario->getFoneCelular()?>">
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="observacao">Observação:</label>
            <div class="col-sm-10">
                <textarea class="form-control" rows="5" id="observacao" name="observacao" placeholder="Espaço para informações adicionais do usuário"><?php echo $usuario->getObservacao()?></textarea>
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="situacao">Situação:</label>
            <div class="col-sm-10">
                <label class="radio-inline"><input type="radio" name="situacao" value="0" <?php echo ( $usuario->getSituacao() == 0 ) ? 'checked="checked"' : '' ?> ><?php echo $usuario->getSituacaoExtensoParam(0)?></label>
                <label class="radio-inline"><input type="radio" name="situacao" value="1" <?php echo ( $usuario->getSituacao() == 1 ) ? 'checked="checked"' : '' ?> ><?php echo $usuario->getSituacaoExtensoParam(1)?></label>
            </div>
        </div>
        
    </form>
    
</div>

<script type="text/javascript">
    function voltar() {
        postViaJS('', {controle: 'Usuarios', acao: 'listar'});
    }
</script>

<?php include 'pageclose.php';