<?php
    $v_params = $this->getParams();
    
    $mensagem = "";
    if (array_key_exists('mensagem', $v_params)) {
        $mensagem = $v_params['mensagem'];
    }
    
    $registro = new TiposAtividadesVo();
    if (array_key_exists('registro', $v_params)) {
        $registro = $v_params['registro'];
    }
?>

<?php include 'pageopen.php' ?>

<div class="container">
    
    <div class="page-header">
        <h3>Tipos de Atividades<small> / Tela de Cadastro</small></h3>
    </div>
    
    <?php
    if (!empty($mensagem)) {
        if (substr($mensagem,0,1) == "N") {
            echo '<div class="alert alert-danger"><strong>ERRO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
        if (substr($mensagem,0,1) == "S") {
            echo '<div class="alert alert-success"><strong>SUCESSO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
    }
    ?>
    
    <form class="form-horizontal" role="form" method="post">
        
        <button type="button" class="btn btn-default" onclick="javascript:voltar();">
            <span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Voltar
        </button>
        
        <button type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;&nbsp;Salvar 
        </button>
        
        <p><br /></p>
        
        <input type='hidden' name='controle' value='TiposAtividades'>
        <input type='hidden' name='acao' value='salvar'>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="id">Código:</label>
            <div class="col-sm-1">
                <input type="hidden" id="id" name="id" value="<?php echo $registro->getId() ?>">
                <input type="text" class="form-control" id="id" name="id" value="<?php echo $registro->getId()?>" disabled="disabled">
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="descricao">Descrição:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="descricao" name="descricao" value="<?php echo $registro->getDescricao()?>">
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="situacao">Situação:</label>
            <div class="col-sm-4">
                <label class="radio-inline"><input type="radio" name="situacao" value="0" <?php echo ( $registro->getSituacao() == 0 ) ? 'checked="checked"' : '' ?> ><?php echo $registro->getSituacaoExtensoParam(0)?></label>
                <label class="radio-inline"><input type="radio" name="situacao" value="1" <?php echo ( $registro->getSituacao() == 1 ) ? 'checked="checked"' : '' ?> ><?php echo $registro->getSituacaoExtensoParam(1)?></label>
            </div>
        </div>
        
    </form>
    
</div>

<script type="text/javascript">
    function voltar() {
        postViaJS('', {controle: 'TiposAtividades', acao: 'listar'});
    }
</script>

<?php include 'pageclose.php';