<?php
    $v_params = $this->getParams();
    
    $mensagem = "";
    if (array_key_exists('mensagem', $v_params)) {
        $mensagem = $v_params['mensagem'];
    }
    
    $registro = new PerfisVo();
    if (array_key_exists('registro', $v_params)) {
        $registro = $v_params['registro'];
    }
    
    $perfisPermissoes = array();
    if (array_key_exists('perfisPermissoes', $v_params)) {
        $perfisPermissoes = $v_params['perfisPermissoes'];
    }
?>

<?php include 'pageopen.php' ?>

<div class="container">
    
    <div class="page-header">
        <h3>Perfis<small> / Tela de Cadastro</small></h3>
    </div>
    
    <?php
    if (!empty($mensagem)) {
        if (substr($mensagem,0,1) == "N") {
            echo '<div class="alert alert-danger"><strong>ERRO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
        if (substr($mensagem,0,1) == "S") {
            echo '<div class="alert alert-success"><strong>SUCESSO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
    }
    ?>
    
    <form class="form-horizontal" role="form" method="post">
        
        <button type="button" class="btn btn-default" onclick="javascript:voltar();">
            <span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Voltar
        </button>
        
        <button type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;&nbsp;Salvar 
        </button>
        
        <?php if (!Functions::isEmpty($registro->getId())) { ?>
            <button type="button" class="btn btn-default" onclick="javascript:incluir(<?php echo $registro->getId() ?>);">
                <span class="glyphicon glyphicon-file"></span>&nbsp;Nova Permissão
            </button>
        <?php } ?>
        
        <p><br /></p>
        
        <input type='hidden' name='controle' value='Perfis'>
        <input type='hidden' name='acao' value='salvar'>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="id">Código:</label>
            <div class="col-sm-1">
                <input type="hidden" id="id" name="id" value="<?php echo $registro->getId()?>">
                <input type="text" class="form-control" id="id" name="id" value="<?php echo $registro->getId()?>" disabled="disabled">
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="descricao">Descrição:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="descricao" name="descricao" value="<?php echo $registro->getDescricao()?>">
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="administrador">Administrador:</label>
            <div class="col-sm-4">
                <label class="radio-inline"><input type="radio" name="administrador" value="0" <?php echo ( $registro->getAdministrador() == 0 ) ? 'checked="checked"' : '' ?> ><?php echo $registro->getAdministradorExtensoParam(0)?></label>
                <label class="radio-inline"><input type="radio" name="administrador" value="1" <?php echo ( $registro->getAdministrador() == 1 ) ? 'checked="checked"' : '' ?> ><?php echo $registro->getAdministradorExtensoParam(1)?></label>
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="funcionario">Funcionário:</label>
            <div class="col-sm-4">
                <label class="radio-inline"><input type="radio" name="funcionario" value="0" <?php echo ( $registro->getFuncionario() == 0 ) ? 'checked="checked"' : '' ?> ><?php echo $registro->getFuncionarioExtensoParam(0)?></label>
                <label class="radio-inline"><input type="radio" name="funcionario" value="1" <?php echo ( $registro->getFuncionario() == 1 ) ? 'checked="checked"' : '' ?> ><?php echo $registro->getFuncionarioExtensoParam(1)?></label>
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="cliente">Cliente:</label>
            <div class="col-sm-4">
                <label class="radio-inline"><input type="radio" name="cliente" value="0" <?php echo ( $registro->getCliente() == 0 ) ? 'checked="checked"' : '' ?> ><?php echo $registro->getClienteExtensoParam(0)?></label>
                <label class="radio-inline"><input type="radio" name="cliente" value="1" <?php echo ( $registro->getCliente() == 1 ) ? 'checked="checked"' : '' ?> ><?php echo $registro->getClienteExtensoParam(1)?></label>
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="situacao">Situação:</label>
            <div class="col-sm-4">
                <label class="radio-inline"><input type="radio" name="situacao" value="0" <?php echo ( $registro->getSituacao() == 0 ) ? 'checked="checked"' : '' ?> ><?php echo $registro->getSituacaoExtensoParam(0)?></label>
                <label class="radio-inline"><input type="radio" name="situacao" value="1" <?php echo ( $registro->getSituacao() == 1 ) ? 'checked="checked"' : '' ?> ><?php echo $registro->getSituacaoExtensoParam(1)?></label>
            </div>
        </div>
        
    </form>
    
    <p><br /></p>
    
    <?php if (!Functions::isEmpty($registro->getId())) { ?>
        <div class="well well-sm"><b>Permissões</b></div>

        <table class="table table-striped">

            <thead>
                <tr>
                    <th class="col-sm-1">#</th>
                    <th class="col-sm-8">Tipo de Sistema</th>
                    <th class="col-sm-2">Situação</th>
                    <th class="col-sm-1">Ações</th>
                </tr>
            </thead>

            <tbody>
                <?php foreach($perfisPermissoes AS $perfilPermissao) { ?>
                <tr>
                    <td><?php echo $perfilPermissao->getId()?></td>
                    <td><?php echo $perfilPermissao->getTipoSistema()->getDescricao()?></td>
                    <td><?php echo $perfilPermissao->getSituacaoExtenso()?></td>
                    <td>
                        <button type="button" class="btn btn-default btn-xs" onclick="javascript:editar(<?php echo $registro->getId()?>,<?php echo $perfilPermissao->getId()?>);">
                            <span class="glyphicon glyphicon-cog"></span>&nbsp;Alterar
                        </button>
                        <!--
                        <button type="button" class="btn btn-default btn-xs" onclick="javascript:excluir(<?php echo $registro->getId()?>,<?php echo $perfilPermissao->getId()?>);">
                            <span class="glyphicon glyphicon-trash"></span>&nbsp;Excluir
                        </button>
                        -->
                    </td>
                </tr>
                <?php } ?>
            </tbody>
            
        </table>
    <?php } ?>
    
</div>

<script type="text/javascript">
    function voltar() {
        postViaJS('', {controle: 'Perfis', acao: 'listar'});
    }
    function incluir(perfilCodigo) {
        postViaJS('', {controle: 'PerfisPermissoes', acao: 'cadastrar', perfilCodigo: perfilCodigo});
    }
    function editar(perfilCodigo, codigo) {
        postViaJS('', {controle: 'PerfisPermissoes', acao: 'cadastrar', perfilCodigo: perfilCodigo, id: codigo});
    }
    function excluir(perfilCodigo, codigo) {
        postViaJS('', {controle: 'PerfisPermissoes', acao: 'excluir', perfilCodigo: perfilCodigo, id: codigo});
    }
</script>

<?php include 'pageclose.php';