<?php
    $v_params = $this->getParams();
    
    $mensagem = "";
    if (array_key_exists('mensagem', $v_params)) {
        $mensagem = $v_params['mensagem'];
    }
    
    $atividade = new AtividadesVo();
    if (array_key_exists('atividade', $v_params)) {
        $atividade = $v_params['atividade'];
    }
    
    $situacoes = array();
    if (array_key_exists('situacoes', $v_params)) {
        $situacoes = $v_params['situacoes'];
    }
    
    $usuarios = array();
    if (array_key_exists('usuarios', $v_params)) {
        $usuarios = $v_params['usuarios'];
    }
    
    $empresas = array();
    if (array_key_exists('empresas', $v_params)) {
        $empresas = $v_params['empresas'];
    }
    
    $tiposAtividades = array();
    if (array_key_exists('tiposAtividades', $v_params)) {
        $tiposAtividades = $v_params['tiposAtividades'];
    }
    
    $apontamentos = array();
    if (array_key_exists('apontamentos', $v_params)) {
        $apontamentos = $v_params['apontamentos'];
    }
    
    $outraAtividade = "";
    if (isset($v_params['outraAtividade'])) {
        $outraAtividade = $v_params['outraAtividade'];
    }
    
    $caller = "";
    if (isset($v_params['caller'])) {
	$caller = $v_params['caller'];
    }
    
    if ($_SESSION['perfilAdministrador'] == 1) {
        $dataIni = "";
        $dataFim = "";
        
        $exibeUsuarioAberto = true;
        $usuarioCodigo = "";
        $usuarioNome = "";
        
        $exibeAcoesApontamentos = true;
    } else {
        $dataIni = date("Y-m-d", strtotime("-30 days"));
        $dataFim = date("Y-m-d");
        
        $exibeUsuarioAberto = false;
        $usuarioCodigo = $_SESSION['usuarioCodigo'];
        $usuarioNome = $_SESSION['usuarioNome'];
        
        $exibeAcoesApontamentos = false;
    }
    
    if (Functions::isEmpty($atividade->getId())) {
        $inclusao = true;
        $atividadeData = date("d/m/Y");
        $situacaoCodigo = $_SESSION['situacaoEmAndamento'];
        $situacaoDescricao = "Em Andamento";
    } else {
        $inclusao = false;
        $atividadeData = "";
        $situacaoCodigo = "";
        $situacaoDescricao = "";
    }
    
    if (Functions::isEmpty($_SESSION['empresaCodigo'])) {
        $exibeEmpresaAberta = true;
        $empresaCodigo = "";
        $empresaDescricao = "";
    } else {
        $exibeEmpresaAberta = false;
        $empresaCodigo = $_SESSION['empresaCodigo'];
        $empresaDescricao = $_SESSION['empresaDescricao'];
    }
    
    if (($_SESSION['perfilAdministrador'] == 0) && (!$inclusao) && (($atividade->getSituacao()->getId() == $_SESSION['situacaoFinalizada']) || ($atividade->getSituacao()->getId() == $_SESSION['situacaoCancelada']))) {
        $exibeControlesAbertos = false;
    } else {
        $exibeControlesAbertos = true;
    }
?>

<?php include 'pageopen.php' ?>

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script>
    $(document).ready(function() {
        $(".datepicker").datepicker({dateFormat: 'dd/mm/yy'});
    });
</script>

<div class="container">
    
    <div class="page-header">
        <h3>Atividades<small> / Tela de Cadastro</small></h3>
    </div>
    
    <?php
    if (!empty($mensagem)) {
        if (substr($mensagem,0,1) == "N") {
            echo '<div class="alert alert-danger"><strong>ERRO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
        if (substr($mensagem,0,1) == "S") {
            echo '<div class="alert alert-success"><strong>SUCESSO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
    }
    ?>
    
    <form class="form-horizontal" role="form" method="post" onsubmit="return verifica();">
        
        <button type="button" class="btn btn-default" onclick="javascript:voltar();">
            <span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Voltar
        </button>
        
        
        <?php if ($exibeControlesAbertos) { ?>
            <button type="submit" class="btn btn-default">
                <span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;&nbsp;Salvar 
            </button>

            <?php if (!$inclusao) { ?>
                <button type="button" class="btn btn-default" onclick="javascript:finalizar(<?php echo $atividade->getId() ?>);">
                    <span class="glyphicon glyphicon-ok-sign"></span>&nbsp;&nbsp;Finalizar
                </button>

                <button type="button" class="btn btn-default" onclick="javascript:cancelar(<?php echo $atividade->getId() ?>);">
                    <span class="glyphicon glyphicon-remove-sign"></span>&nbsp;&nbsp;Cancelar
                </button>
            <?php } ?>
        <?php } ?>
        
        <p><br /></p>
        
        <input type='hidden' name='controle' value='atividades'>
        <input type='hidden' name='acao' value='salvarCadastrar'>
        
        <div class="well well-sm"><b>Principal</b></div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="id">Código:</label>
            <div class="col-sm-3">
                <input type="hidden" id="id" name="id" value="<?php echo $atividade->getId() ?>">
                <input type="text" class="form-control" id="id" name="id" value="<?php echo $atividade->getId()?>" disabled="disabled">
            </div>
            <label class="control-label col-sm-2" for="data">Data Abertura:</label>
            <div class="col-sm-3">
                <?php 
                if ($inclusao) {
                    echo '<input type="hidden" name="data" value="' . $atividadeData . '" />';
                    echo '<input type="text" class="form-control datepicker" id="data" name="data" value="' . $atividadeData . '" disabled="disabled" />';
                } else {
                    if ($exibeControlesAbertos) {
                        echo '<input type="text" class="form-control datepicker" id="data" name="data" value="' . $atividade->getData() . '" />';
                    } else {
                        echo '<input type="text" class="form-control datepicker" id="data" name="data" value="' . $atividade->getData() . '" disabled="disabled"/>';
                    }
                } 
                ?>
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="situacao">Situação:</label>
            <div class="col-sm-3">
                <?php
                if ($inclusao) {
                    echo '<input type="hidden" name="situacao" value="' . $situacaoCodigo . '" />';
                    echo '<input type="text" class="form-control" id="situacao" name="situacao" value="' . $situacaoDescricao . '" disabled="disabled" />';
                } else {
                    if ($exibeControlesAbertos) {
                        echo '<select class="form-control" id="situacao" name="situacao">';
                    } else {
                        echo '<select class="form-control" id="situacao" name="situacao" disabled="disabled">';
                    }
                    echo '<option value="">Selecione</option>';
                    foreach($situacoes as $situacao) {
                        if ($atividade->getSituacao() != "" && $situacao->getId() == $atividade->getSituacao()->getId()) {
                            echo '<option value="' . $situacao->getId() . '" selected>' . $situacao->getDescricao() . '</option>';
                        } else {
                            echo '<option value="' . $situacao->getId() . '">' . $situacao->getDescricao() . '</option>';
                        }
                    }
                    echo '</select>';
                }
                ?>
            </div>
            <label class="control-label col-sm-2" for="usuario">Analista:</label>
            <div class="col-sm-3">
                <?php 
                if ($exibeUsuarioAberto) {
                    if ($exibeControlesAbertos) {
                        echo '<select class="form-control" id="usuario" name="usuario">';
                    } else {
                        echo '<select class="form-control" id="usuario" name="usuario" disabled="disabled">';
                    }
                    echo '<option value="">Selecione</option>';
                    foreach($usuarios as $usuario) {
                        if ($atividade->getUsuario() != "" && $usuario->getId() == $atividade->getUsuario()->getId()) {
                            echo '<option value="' . $usuario->getId() . '" selected>' . $usuario->getNome() . '</option>';
                        } else {
                            echo '<option value="' . $usuario->getId() . '">' . $usuario->getNome() . '</option>';
                        }
                    }
                    echo '</select>';
                } else {
                    echo '<input type="hidden" name="usuario" value="' . $usuarioCodigo . '" />';
                    echo '<input type="text" class="form-control" id="usuario" name="usuario" value="' . $usuarioNome . '" disabled="disabled" />';
                }
                ?>
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="empresa">Empresa:</label>
            <div class="col-sm-3">
                <?php 
                if ($exibeEmpresaAberta) {
                    if ($exibeControlesAbertos) {
                        echo '<select class="form-control" id="empresa" name="empresa">';
                    } else {
                        echo '<select class="form-control" id="empresa" name="empresa" disabled="disabled">';
                    }
                    echo '<option value="">Selecione</option>';
                    foreach($empresas as $empresa) {
                        if ($atividade->getEmpresa() != "" && $empresa->getId() == $atividade->getEmpresa()->getId()) {
                            echo '<option value="' . $empresa->getId() . '" selected>' . $empresa->getDescricao() . '</option>';
                        } else {
                            echo '<option value="' . $empresa->getId() . '">' . $empresa->getDescricao() . '</option>';
                        }
                    }
                    echo '</select>';
                } else {
                    echo '<input type="hidden" name="empresa" value="' . $empresaCodigo . '" />';
                    echo '<input type="text" class="form-control" id="empresa" name="empresa" value="' . $empresaDescricao . '" disabled="disabled" />';
                }
                ?>
            </div>
            <label class="control-label col-sm-2" for="tipoAtividade">Tipo de Atividade:</label>
            <div class="col-sm-3">
                <?php
                if ($exibeControlesAbertos) {
                    echo '<select class="form-control" id="tipoAtividade" name="tipoAtividade">';
                } else {
                    echo '<select class="form-control" id="tipoAtividade" name="tipoAtividade" disabled="disabled">';
                }
                echo '<option value="">Selecione</option>';
                foreach($tiposAtividades as $tipoAtividade) {
                    if ($atividade->getTipoAtividade() != "" && $tipoAtividade->getId() == $atividade->getTipoAtividade()->getId()) {
                        echo '<option value="' . $tipoAtividade->getId() . '" selected>' . $tipoAtividade->getDescricao() . '</option>';
                    } else {
                        echo '<option value="' . $tipoAtividade->getId() . '">' . $tipoAtividade->getDescricao() . '</option>';
                    }
                }
                echo '</select>';
                ?>
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="id">Assunto:</label>
            <div class="col-sm-8">
                <?php
                if ($exibeControlesAbertos) {
                    echo '<input type="text" class="form-control" id="assunto" name="assunto" value="' . $atividade->getAssunto() . '">';
                } else {
                    echo '<input type="text" class="form-control" id="assunto" name="assunto" value="' . $atividade->getAssunto() . '" disabled="disabled">';
                }
                ?>
            </div>
        </div>
        
        <!-- include summernote css/js-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.1/summernote.css" rel="stylesheet">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.1/summernote.js"></script>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="observacao">Descrição:</label>
            <div class="col-sm-8">
                <input type="hidden" id="observacao" name="observacao" value="">
                <div id="summernote" name="summernote"><p><?php echo $atividade->getObservacao()?></p></div>
            </div>
            <script>
                $(document).ready(function() {
                    $('#summernote').summernote({
                        height: 200
                    });
                });
            </script>
            <?php if (!$exibeControlesAbertos) { ?>
            <script>
                $(document).ready(function() {
                    $('#summernote').summernote('disable');
                });
            </script>
            <?php } ?>
        </div>
        
    </form>
    
    <?php if (!$inclusao) { ?>
        <div class="well well-sm"><b>Apontamentos</b></div>
        
        <?php if ($exibeControlesAbertos) { ?>
            <?php if ($exibeAcoesApontamentos) { ?>
                <button type="button" class="btn btn-default" onclick="javascript:incluir(<?php echo $atividade->getId()?>);">
                    <span class="glyphicon glyphicon-file"></span>&nbsp;&nbsp;Novo
                </button>
            <?php } ?>

            <button type="button" class="btn btn-default" onclick="javascript:iniciar(<?php echo $atividade->getId()?>);">
                <span class="glyphicon glyphicon-play"></span>&nbsp;&nbsp;Iniciar
            </button>

            <button type="button" class="btn btn-default" onclick="javascript:parar(<?php echo $atividade->getId()?>);">
                <span class="glyphicon glyphicon-stop"></span>&nbsp;&nbsp;Parar
            </button>
        <?php } ?>
        
        <p><br /></p>
        
        <table class="table table-striped">

            <thead>
                <tr>
                    <th class="col-sm-3">Funcionário</th>
                    <th class="col-sm-1">Início</th>
                    <th class="col-sm-1">Fim</th>
                    <th class="col-sm-1">Duração</th>
                    <th class="col-sm-4">Observação</th>
                    <?php if (($exibeControlesAbertos) && ($exibeAcoesApontamentos)) { ?>
                        <th class="col-sm-2">Ações</th>
                    <?php } ?>
                </tr>
            </thead>

            <tbody>
            <?php foreach ($apontamentos AS $apontamento) { ?>
                <tr>
                    <td><?php echo $apontamento->getUsuario()->getNome()?></td>
                    <td><?php echo $apontamento->getDataInicio()?></td>
                    <td><?php echo $apontamento->getDataFim()?></td>
                    <td><?php echo $apontamento->getApontado()?></td>
                    <td><?php echo $apontamento->getObservacao()?></td>
                    <?php if (($exibeControlesAbertos) && ($exibeAcoesApontamentos)) { ?>
                        <td>
                            <button type="button" class="btn btn-default btn-xs" onclick="javascript:editar(<?php echo $apontamento->getId()?>,<?php echo $atividade->getId()?>);">
                                <span class="glyphicon glyphicon-cog"></span>&nbsp;Alterar
                            </button>
                            <button type="button" class="btn btn-default btn-xs" onclick="javascript:excluir(<?php echo $apontamento->getId()?>);">
                                <span class="glyphicon glyphicon-trash"></span>&nbsp;Excluir
                            </button>
                        </td>
                    <?php } ?>
                </tr>
            <?php } ?>
            </tbody>
            
        </table>
    <?php } ?>
    
</div>

<script>
    function voltar() {
        postViaJS('', {controle: 'Atividades', acao: 'filtrar'});
    }
    function finalizar(atividadeCodigo) {
        postViaJS('', {controle: 'Atividades', acao: 'finalizar', id: atividadeCodigo});
    }
    function cancelar(atividadeCodigo) {
        postViaJS('', {controle: 'Atividades', acao: 'cancelar', id: atividadeCodigo});
    }
    function incluir(atividadeCodigo) {
        postViaJS('', {controle: 'Apontamentos', acao: 'cadastrar', atividade: atividadeCodigo});
    }
    function editar(apontamentoCodigo, atividadeCodigo) {
        postViaJS('', {controle: 'Apontamentos', acao: 'cadastrar', id: apontamentoCodigo, atividade: atividadeCodigo});
    }
    function excluir(apontamentoCodigo) {
        postViaJS('', {controle: 'Apontamentos', acao: 'excluir', id: apontamentoCodigo});
    }
    function iniciar(atividadeCodigo) {
        var observacao = prompt("Informe a observação para o início do apontamento");
        if (observacao != null) {
            postViaJS('', {controle: 'Apontamentos', acao: 'iniciar', atividade: atividadeCodigo, observacao: observacao});
        }
    }
    function parar(atividadeCodigo) {
        var observacao = prompt("Informe a observação para o término/pausa do apontamento");
        if (observacao != null) {
            postViaJS('', {controle: 'Apontamentos', acao: 'parar', atividade: atividadeCodigo, observacao: observacao});
        }
    }
    function iniciar2(atividadeIniciar, atividadeVisualizar) {
        var observacao = "Iniciado automaticamente";
        if (observacao != null) {
            postViaJS('', {controle: 'Apontamentos', acao: 'iniciar', atividade: atividadeIniciar, observacao: observacao, visualizar: atividadeVisualizar});
        }
    }
    function parar2(atividadeParar, atividadeVisualizar) {
        var observacao = "Parado/pausado automaticamente";
        if (observacao != null) {
            postViaJS('', {controle: 'Apontamentos', acao: 'parar', atividade: atividadeParar, observacao: observacao, visualizar: atividadeVisualizar});
        }
    }
    function verifica() {
        var markupStr = $('#summernote').summernote('code');
        document.getElementById('observacao').value = markupStr;
        return true;
    }
</script>

<?php include 'pageclose.php';
