<?php
    $v_params = $this->getParams();
    
    $mensagem = "";
    if (array_key_exists('mensagem', $v_params)) {
        $mensagem = $v_params['mensagem'];
    }
    
    $usuario = new UsuariosVo();
    if (array_key_exists('usuario', $v_params)) {
        $usuario = $v_params['usuario'];
    }
?>

<?php include 'pageopen.php' ?>

<div class="container">
    
    <div class="page-header">
        <h3>Usuários<small> / Tela de Cadastro</small></h3>
    </div>
    
    <?php
    if (!empty($mensagem)) {
        if (substr($mensagem,0,1) == "N") {
            echo '<div class="alert alert-danger"><strong>ERRO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
        if (substr($mensagem,0,1) == "S") {
            echo '<div class="alert alert-success"><strong>SUCESSO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
    }
    ?>
    
    <form class="form-horizontal" role="form" method="post">
        
        <button type="button" class="btn btn-default" onclick="javascript:voltar();">
            <span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Voltar
        </button>
        
        <button type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;&nbsp;Salvar 
        </button>
        
        <p><br /></p>
        
        <input type='hidden' name='controle' value='Usuarios'>
        <input type='hidden' name='acao' value='salvarAtualizar'>
        
        <div class="well well-sm"><b>Dados Básicos</b></div>
        
        <input type="hidden" id="id" name="id" value="<?php echo $usuario->getId() ?>">
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="email">Usuário:</label>
            <div class="col-sm-4">
                <input type="hidden" id="email" name="email" value="<?php echo $usuario->getEmail()?>">
                <input type="text" class="form-control" value="<?php echo $usuario->getEmail()?>" disabled="disabled">
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="nome">Nome:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="nome" name="nome" value="<?php echo $usuario->getNome()?>">
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="foneComercial">Fone Comercial:</label>
            <div class="col-sm-2">
                <input type="text" class="form-control" id="foneComercial" name="foneComercial" value="<?php echo $usuario->getFoneComercial()?>">
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="foneCelular">Fone Celular:</label>
            <div class="col-sm-2">
                <input type="text" class="form-control" id="foneCelular" name="foneCelular" value="<?php echo $usuario->getFoneCelular()?>">
            </div>
        </div>
        
        <div class="well well-sm"><b>Alterar a Senha</b></div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="senhaAtual">Senha Atual:</label>
            <div class="col-sm-2">
                <input type="password" class="form-control" id="senha" name="senhaAtual" value="">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="senhaNova1">Nova Senha:</label>
            <div class="col-sm-2">
                <input type="password" class="form-control" id="senha" name="senhaNova1" value="">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="senhaNova2">Repita a Nova Senha:</label>
            <div class="col-sm-2">
                <input type="password" class="form-control" id="senha" name="senhaNova2" value="">
            </div>
        </div>
        
    </form>
    
</div>

<script type="text/javascript">
    function voltar() {
        postViaJS('', {controle: 'Index', acao: 'index'});
    }
</script>

<?php include 'pageclose.php';