<?php
    $v_params = $this->getParams();
    
    $mensagem = "";
    if (array_key_exists('mensagem', $v_params)) {
        $mensagem = $v_params['mensagem'];
    }
    
    $apontamento = new ApontamentosVo();
    if (array_key_exists('apontamento', $v_params)) {
        $apontamento = $v_params['apontamento'];
    }
    
    $usuarios = array();
    if (array_key_exists('usuarios', $v_params)) {
        $usuarios = $v_params['usuarios'];
    }
    
    $atividade = "";
    if (array_key_exists('atividade', $v_params)) {
        $atividade = $v_params['atividade'];
    }
    
    $chamado = "";
    if (array_key_exists('chamado', $v_params)) {
        $chamado = $v_params['chamado'];
    }
    
    if ($_SESSION['perfilAdministrador'] == 1) {
        $exibeUsuarioAberto = true;
        $usuarioCodigo = "";
        $usuarioNome = "";
    } else {
        $exibeUsuarioAberto = false;
        $usuarioCodigo = $_SESSION['usuarioCodigo'];
        $usuarioNome = $_SESSION['usuarioNome'];
    }
?>

<?php include 'pageopen.php' ?>

<script>
    function atualizarUsuarioModal() {
        var ajax;
        if (window.XMLHttpRequest)
            ajax = new XMLHttpRequest();
        else
            ajax = new ActiveXObject("Microsoft.XMLHTTP");

        ajax.onreadystatechange = function() {
            if (ajax.readyState == 4 && ajax.status == 200) {
                document.getElementById("usuarioModal").innerHTML = ajax.responseText;
            }
        }
        ajax.open("POST", "?controle=Usuarios&acao=ajaxExibeContatosUsuario", true);
        ajax.setRequestHeader("Content-type","application/x-www-form-urlencoded");
        ajax.send("usuarioCodigo=" + document.getElementById("usuario").value);
    }
</script>

<div class="container">
    
    <div class="page-header">
        <h3>Apontamentos<small> / Tela de Cadastro</small></h3>
    </div>
    
    <?php
    if (!empty($mensagem)) {
        if (substr($mensagem,0,1) == "N") {
            echo '<div class="alert alert-danger"><strong>ERRO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
        if (substr($mensagem,0,1) == "S") {
            echo '<div class="alert alert-success"><strong>SUCESSO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
    }
    ?>
    
    <form class="form-horizontal" role="form" method="post" name="form" onsubmit="return verifica();">
        
        <?php
        if (!Functions::isEmpty($atividade)) {
            echo '<button type="button" class="btn btn-default" onclick="javascript:voltarAtividade(' . $atividade . ');">';
            echo '<span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Voltar';
            echo '</button>';
        }
        if (!Functions::isEmpty($chamado)) {
            echo '<button type="button" class="btn btn-default" onclick="javascript:voltarChamado(' . $chamado . ');">';
            echo '<span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Voltar';
            echo '</button>';
        }
        ?>
        
        <button type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;&nbsp;Salvar 
        </button>
        
        <p><br /></p>
        
        <input type='hidden' name='controle' value='Apontamentos'>
        <input type='hidden' name='acao' value='salvarCadastrar'>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="id">Código:</label>
            <div class="col-sm-2">
                <input type="hidden" id="id" name="id" value="<?php echo $apontamento->getId() ?>">
                <input type="text" class="form-control" id="id" name="id" value="<?php echo $apontamento->getId()?>" disabled="disabled">
            </div>
        </div>
        
        <div class="form-group">
            <?php
            if (!Functions::isEmpty($atividade)) {
                echo '<label class="control-label col-sm-2" for="atividade">Atividade:</label>';
                echo '<div class="col-sm-2">';
                echo '  <input type="hidden" id="atividade" name="atividade" value="' . $atividade . '">';
                echo '  <input type="text" class="form-control" id="atividade" name="atividade" value="' . $atividade . '" disabled="disabled">';
                echo '</div>';
            }
            if (!Functions::isEmpty($chamado)) {
                echo '<label class="control-label col-sm-2" for="chamado">Chamado:</label>';
                echo '<div class="col-sm-2">';
                echo '  <input type="hidden" id="chamado" name="chamado" value="' . $chamado . '">';
                echo '  <input type="text" class="form-control" id="chamado" name="chamado" value="' . $chamado . '" disabled="disabled">';
                echo '</div>';
            }
            ?>
            <label class="control-label col-sm-1" for="usuario">Usuário:</label>
            <div class="col-sm-5">
                <div class="input-group">   
                    <div class="input-group-addon" data-toggle="modal" data-target="#usuarioModal">
                        <span class="glyphicon glyphicon-info-sign"></span> 
                    </div>
                    <?php 
                    if ($exibeUsuarioAberto) {
                        echo '<select class="form-control" id="usuario" name="usuario" onchange="atualizarUsuarioModal()">';
                        echo '<option value="">Selecione</option>';
                        foreach($usuarios as $usuario) {
                            if ($apontamento->getUsuario() != "" && $usuario->getId() == $apontamento->getUsuario()->getId()) {
                                echo '<option value="' . $usuario->getId() . '" selected>' . $usuario->getNome() . '</option>';
                            } else {
                                echo '<option value="' . $usuario->getId() . '">' . $usuario->getNome() . '</option>';
                            }
                        }
                        echo '</select>';
                    } else {
                        echo '<input type="hidden" name="usuario" value="' . $usuarioCodigo . '" />';
                        echo '<input type="text" class="form-control" id="usuario" name="usuario" value="' . $usuarioNome . '" disabled="disabled" />';
                    }
                    ?>
                    <div id="usuarioModal" class="modal fade" role="dialog">
                        
                    </div>
                </div>
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="dataInicio">Início:</label>
            <div class="col-sm-2">
                <input type="text" class="form-control" id="dataInicio" name="dataInicio" placeholder="dd/mm/aaaa hh:mm:ss" value="<?php echo $apontamento->getDataInicio()?>">
            </div>
            <label class="control-label col-sm-1" for="dataFim">Fim:</label>
            <div class="col-sm-2">
                <input type="text" class="form-control" id="dataFim" name="dataFim" placeholder="dd/mm/aaaa hh:mm:ss" value="<?php echo $apontamento->getDataFim()?>">
            </div>
            <label class="control-label col-sm-1" for="dataFim">Duração:</label>
            <div class="col-sm-2">
                <div class="input-group">   
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-time"></span> 
                    </div>
                    <input type="text" class="form-control" id="apontado" name="apontado" value="<?php echo $apontamento->getApontado()?>" disabled="disabled">
                </div>
            </div>
        </div>
        
        <?php if (Functions::isEmpty($apontamento->getApontado())) {?>
            <div class="form-group">
                <label class="control-label col-sm-2" for="avaliacao">Tipo Avaliação:</label>
                <div class="col-sm-5">
                    <input type="hidden" id="avaliacao" name="avaliacao" value="<?php echo $apontamento->getAvaliacao()?>" />
                    <input type="text" class="form-control" id="avaliacao" name="avaliacao" value="" disabled="disabled">
                </div>
                <label class="control-label col-sm-1" for="faturado">Faturado:</label>
                <div class="col-sm-2">
                    <div class="input-group">   
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-time"></span> 
                        </div>
                        <input type="hidden" id="faturado" name="faturado" value="<?php echo $apontamento->getFaturado()?>" />
                        <input type="text" class="form-control" id="faturado" name="faturado" value="" disabled="disabled">
                    </div>
                </div>
            </div>
        <?php } else { ?>
            <div class="form-group">
                <label class="control-label col-sm-2" for="avaliacao">Tipo de Avaliação:</label>
                <div class="col-sm-5">
                    <select class="form-control" id="avaliacao" name="avaliacao" onchange="verificaHorasFaturar()">
                        <option value=""  <?php echo $apontamento->getAvaliacao() == ""  ? "selected" : "" ?>>Selecione</option>
                        <option value="9" <?php echo $apontamento->getAvaliacao() == "9" ? "selected" : "" ?>>Não Avaliado</option>
                        <option value="1" <?php echo $apontamento->getAvaliacao() == "1" ? "selected" : "" ?>>Faturado Integral</option>
                        <option value="2" <?php echo $apontamento->getAvaliacao() == "2" ? "selected" : "" ?>>Faturado Parcial</option>
                        <option value="3" <?php echo $apontamento->getAvaliacao() == "3" ? "selected" : "" ?>>Não Faturado</option>
                    </select>
                </div>
                <label class="control-label col-sm-1" for="faturado">Faturado:</label>
                <div class="col-sm-2">
                    <div class="input-group">   
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-time"></span> 
                        </div>
                        <input type="text" class="form-control" id="faturado" name="faturado" value="<?php echo $apontamento->getFaturado()?>">
                    </div>
                </div>
            </div>
        <?php } ?>
        
        <!-- include summernote css/js-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.1/summernote.css" rel="stylesheet">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.1/summernote.js"></script>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="observacao">Observação:</label>
            <div class="col-sm-8">
                <input type="hidden" id="observacao" name="observacao" value="">
                <div id="summernote" name="summernote"><p><?php echo $apontamento->getObservacao()?></p></div>
            </div>
            <script>
                $(document).ready(function() {
                    $('#summernote').summernote({
                        height: 200
                    });
                });
            </script>
        </div>
        
    </form>
    
</div>

<script type="text/javascript">
    function voltarAtividade(atividadeCodigo) {
        postViaJS('', {controle: 'Atividades', acao: 'cadastrar', id: atividadeCodigo});
    }
    function voltarChamado(chamadoCodigo) {
        postViaJS('', {controle: 'Chamados', acao: 'cadastrar', id: chamadoCodigo});
    }
    function verificaHorasFaturar() {
        if (document.form.elements['avaliacao'].value == "" ) {
            document.form.elements['faturado'].value = "00:00:00";
      	}
      	if (document.form.elements['avaliacao'].value == "0") {
            document.form.elements['faturado'].value = "00:00:00";
      	}
      	if (document.form.elements['avaliacao'].value == "1") {
            document.form.elements['faturado'].value = document.form.elements['apontado'].value;
      	}
      	if (document.form.elements['avaliacao'].value == "2") {
            document.form.elements['faturado'].value = document.form.elements['apontado'].value;
      	}
        document.form.elements['faturado'].focus();
    }
    function verifica() {
        var markupStr = $('#summernote').summernote('code');
        document.getElementById('observacao').value = markupStr;
        return true;
    }
    atualizarUsuarioModal();
</script>

<?php include 'pageclose.php';