<?php
    $v_params = $this->getParams();
    
    $mensagem = "";
    if (array_key_exists('mensagem', $v_params)) {
        $mensagem = $v_params['mensagem'];
    }
    
    $perfil = new PerfisVo();
    if (array_key_exists('perfil', $v_params)) {
        $perfil = $v_params['perfil'];
    }
    
    $registro = new PerfisPermissoesVo();
    if (array_key_exists('registro', $v_params)) {
        $registro = $v_params['registro'];
    }
    
    $perfis = array();
    if (array_key_exists('perfis', $v_params)) {
        $perfis = $v_params['perfis'];
    }
    
    $tiposSistemas = array();
    if (array_key_exists('tiposSistemas', $v_params)) {
        $tiposSistemas = $v_params['tiposSistemas'];
    }
?>

<?php include 'pageopen.php' ?>

<div class="container">
    
    <div class="page-header">
        <h3>Permissões do Perfil<small> / Tela de Cadastro</small></h3>
    </div>
    
    <?php
    if (!empty($mensagem)) {
        if (substr($mensagem,0,1) == "N") {
            echo '<div class="alert alert-danger"><strong>ERRO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
        if (substr($mensagem,0,1) == "S") {
            echo '<div class="alert alert-success"><strong>SUCESSO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
    }
    ?>
    
    <form class="form-horizontal" role="form" method="post">
        
        <button type="button" class="btn btn-default" onclick="javascript:voltar(<?php echo $perfil->getId()?>);">
            <span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;Voltar
        </button>
        
        <button type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;&nbsp;Salvar 
        </button>
        
        <p><br /></p>
        
        <input type='hidden' name='controle' value='PerfisPermissoes'>
        <input type='hidden' name='acao' value='salvar'>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="id">Código:</label>
            <div class="col-sm-10">
                <input type="hidden" id="id" name="id" value="<?php echo $registro->getId() ?>">
                <input type="text" class="form-control" id="id" name="id" placeholder="Será gerado automaticamente pelo sistema" value="<?php echo $registro->getId()?>" disabled="disabled">
            </div>
        </div>
        
        <?php if (!Functions::isEmpty($perfil->getId())) { ?>
            <div class="form-group">
                <label class="control-label col-sm-2" for="perfil">Perfil:</label>
                <div class="col-sm-10">
                    <input type="hidden" id="perfil" name="perfil" value="<?php echo $perfil->getId() ?>">
                    <input type="text" class="form-control" id="perfil" name="perfil" placeholder="" value="<?php echo $perfil->getDescricao()?>" disabled="disabled">
                </div>
            </div>
        <?php } else { ?>
            <div class="form-group">
                <label class="control-label col-sm-2" for="perfil">Perfil:</label>
                <div class="col-sm-10">
                    <select class="form-control" id="perfil" name="perfil">
                        <option value="">Selecione</option>
                        <?php
                        foreach($perfis as $perfil) {
                            if ($registro->getPerfil() != "" && $perfil->getId() == $registro->getPerfil()->getId()) {
                                echo '<option value="' . $perfil->getId() . '" selected>' . $perfil->getDescricao() . '</option>';
                            } else {
                                echo '<option value="' . $perfil->getId() . '">' . $perfil->getDescricao() . '</option>';
                            }
                        }
                        ?>
                    </select>
                </div>
            </div>
        <?php } ?>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="tipoSistema">Tipos de Sistemas:</label>
            <div class="col-sm-10">
                <select class="form-control" id="tipoSistema" name="tipoSistema">
                    <option value="">Selecione</option>
                    <?php
                    foreach($tiposSistemas as $tipoSistema) {
                        if ($registro->getTipoSistema() != "" && $tipoSistema->getId() == $registro->getTipoSistema()->getId()) {
                            echo '<option value="' . $tipoSistema->getId() . '" selected>' . $tipoSistema->getDescricao() . '</option>';
                        } else {
                            echo '<option value="' . $tipoSistema->getId() . '">' . $tipoSistema->getDescricao() . '</option>';
                        }
                    }
                    ?>
                </select>
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="situacao">Situação:</label>
            <div class="col-sm-10">
                <label class="radio-inline"><input type="radio" name="situacao" value="0" <?php echo ( $registro->getSituacao() == 0 ) ? 'checked="checked"' : '' ?> ><?php echo $registro->getSituacaoExtensoParam(0)?></label>
                <label class="radio-inline"><input type="radio" name="situacao" value="1" <?php echo ( $registro->getSituacao() == 1 ) ? 'checked="checked"' : '' ?> ><?php echo $registro->getSituacaoExtensoParam(1)?></label>
            </div>
        </div>
        
    </form>
    
</div>

<script type="text/javascript">
    function voltar(perfilCodigo) {
        postViaJS('', {controle: 'Perfis', acao: 'cadastrar', id: perfilCodigo});
    }
</script>

<?php include 'pageclose.php';