<?php
    
    $v_params = $this->getParams();
    
    $mensagem = array();
    if (array_key_exists('mensagem', $v_params)) {
        $mensagem = $v_params['mensagem'];
    }
    
    $periodoInicial = array();
    if (array_key_exists('periodoInicial', $v_params)) {
        $periodoInicial = $v_params['periodoInicial'];
    }
    
    $periodoFinal = array();
    if (array_key_exists('periodoFinal', $v_params)) {
        $periodoFinal = $v_params['periodoFinal'];
    }
    
    $tiposRelatorios = array();
    if (array_key_exists('tiposRelatorios', $v_params)) {
        $tiposRelatorios = $v_params['tiposRelatorios'];
    }
    
    $tipoRelatorio = "";
    if (array_key_exists('tipoRelatorio', $v_params)) {
        $tipoRelatorio = $v_params['tipoRelatorio'];
    }
    
    $exibeEmpresaAberta = 0;
    if (array_key_exists('exibeEmpresaAberta', $v_params)) {
        $exibeEmpresaAberta = $v_params['exibeEmpresaAberta'];
    }
    
    $empresas = array();
    if (array_key_exists('empresas', $v_params)) {
        $empresas = $v_params['empresas'];
    }
    
    $empresa = "";
    if (array_key_exists('empresa', $v_params)) {
        $empresa = $v_params['empresa'];
    }
    
    $situacoes = array();
    if (array_key_exists('situacoes', $v_params)) {
        $situacoes = $v_params['situacoes'];
    }
    
    $situacao = "";
    if (array_key_exists('situacao', $v_params)) {
        $situacao = $v_params['situacao'];
    }
    
    $tiposApontamentos = array();
    if (array_key_exists('tiposApontamentos', $v_params)) {
        $tiposApontamentos = $v_params['tiposApontamentos'];
    }
    
    $tipoApontamento = "";
    if (array_key_exists('tipoApontamento', $v_params)) {
        $tipoApontamento = $v_params['tipoApontamento'];
    }
    
    $exibeTipoAvaliacaoAberta = 0;
    if (array_key_exists('exibeTipoAvaliacaoAberta', $v_params)) {
        $exibeTipoAvaliacaoAberta = $v_params['exibeTipoAvaliacaoAberta'];
    }
    
    $tiposAvaliacoes = array();
    if (array_key_exists('tiposAvaliacoes', $v_params)) {
        $tiposAvaliacoes = $v_params['tiposAvaliacoes'];
    }
    
    $tipoAvaliacao = "";
    if (array_key_exists('tipoAvaliacao', $v_params)) {
        $tipoAvaliacao = $v_params['tipoAvaliacao'];
    }
    
    $chamados = array();
    if (array_key_exists('chamados', $v_params)) {
        $chamados = $v_params['chamados'];
    }
    
    $atividades = array();
    if (array_key_exists('atividades', $v_params)) {
        $atividades = $v_params['atividades'];
    }
    
    $horasFaturadasTotal = '00:00:00';
    
?>

<?php include 'pageopen.php' ?>

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script>
    $(document).ready(function() {
        $(".datepicker").datepicker({dateFormat: 'dd/mm/yy'});
    });
</script>

<div class="container">
    
    <div class="page-header">
        <h3>Relatório de Atendimentos<small> / Analítico</small></h3>
    </div>
    
    <?php
    if (!Functions::isEmpty($mensagem)) {
        if (substr($mensagem,0,1) == "N") {
            echo '<div class="alert alert-danger"><strong>ERRO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
        if (substr($mensagem,0,1) == "S") {
            echo '<div class="alert alert-success"><strong>SUCESSO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
    }
    ?>
    
    <p><br /></p>
    
    <form name="filtros" class="form-horizontal" role="form" method="post" onsubmit="return validar();">
        
        <input type='hidden' name='controle' value='Chamados'>
        <input type='hidden' name='acao' value='relatorioAtendimentos'>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="periodoInicial">Data Abertura (de):</label>
            <div class="col-sm-3">
                <input type="text" class="form-control datepicker" id="periodoInicial" name="periodoInicial" value="<?php echo $periodoInicial; ?>" />
            </div>
            <label class="control-label col-sm-2" for="periodoFinal">Data Abertura (até): </label>
            <div class="col-sm-3">
                <input type="text" class="form-control datepicker" id="periodoFinal" name="periodoFinal" value="<?php echo $periodoFinal; ?>" />
            </div>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="tipoRelatorio">Tipo de Relatório:</label>
            <div class="col-sm-3">
                <select class="form-control" id="tipoRelatorio" name="tipoRelatorio">
                    <option value="">Selecione</option>
                    <?php
                    foreach($tiposRelatorios as $row) {
                        echo '<option value="' . $row->getId() . '">' . $row->getDescricao() . '</option>';
                    }
                    ?>
                </select>
            </div>
            <script>document.filtros.tipoRelatorio.value = "<?php echo $tipoRelatorio ?>";</script>
            <label class="control-label col-sm-2" for="tipoApontamento">Tipo de Apontamento:</label>
            <div class="col-sm-3">
                <select class="form-control" id="tipoApontamento" name="tipoApontamento">
                    <option value="">Selecione</option>
                    <?php
                    foreach($tiposApontamentos as $row) {
                        echo '<option value="' . $row->getId() . '">' . $row->getDescricao() . '</option>';
                    }
                    ?>
                </select>
            </div>
            <script>document.filtros.tipoApontamento.value = "<?php echo $tipoApontamento ?>";</script>
        </div>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="situacao">Situação:</label>
            <div class="col-sm-3">
                <select class="form-control" id="situacao" name="situacao">
                    <option value="">Selecione</option>
                    <?php
                    foreach($situacoes as $row) {
                        echo '<option value="' . $row->getId() . '">' . $row->getDescricao() . '</option>';
                    }
                    ?>
                </select>
            </div>
            <script>document.filtros.situacao.value = "<?php echo $situacao ?>";</script>
            <?php 
            if ($exibeEmpresaAberta == 0) {
                foreach($empresas as $row) {
                    echo '<label class="control-label col-sm-2" for="empresa">Empresa:</label>'
                       . '<div class="col-sm-3">'
                       . '  <input type="text" class="form-control" value="' . $row->getDescricao() . '" disabled="true" />'
                       . '  <input type="hidden" id="empresa" name="empresa" value="' . $row->getId() . '" />'
                       . '</div>';
                }
            } else { ?>
                <label class="control-label col-sm-2" for="empresa">Empresa:</label>
                <div class="col-sm-3">
                    <select class="form-control" id="empresa" name="empresa">
                        <option value="">Selecione</option>
                        <?php
                        foreach($empresas as $row) {
                            echo '<option value="' . $row->getId() . '">' . $row->getDescricao() . '</option>';
                        }
                        ?>
                    </select>
                </div>
                <script>document.filtros.empresa.value = "<?php echo $empresa ?>";</script>
            <?php } ?>
        </div>
        
        <?php if ($exibeTipoAvaliacaoAberta == 0) { ?>
            <input type="hidden" name="tipoAvaliacao" value="<?php echo $tipoAvaliacao ?>" />
        <?php } else { ?>
        <div class="form-group">
            <label class="control-label col-sm-2" for="tipoAvaliacao">Tipo Avaliação:</label>
            <div class="col-sm-3">
                <select class="form-control" id="tipoAvaliacao" name="tipoAvaliacao">
                    <option value="">Selecione</option>
                    <?php
                    foreach($tiposAvaliacoes as $row) {
                        echo '<option value="' . $row->getId() . '">' . $row->getDescricao() . '</option>';
                    }
                    ?>
                </select>
            </div>
            <script>document.filtros.tipoAvaliacao.value = "<?php echo $tipoAvaliacao ?>";</script>
        </div>
        <?php } ?>
        
        <div class="form-group">
            <label class="control-label col-sm-2" for="submit"><br /></label>
            <div class="col-sm-10">
                <button type="submit" name="submit" value="Consultar" class="btn btn-default">
                    <span class="glyphicon glyphicon-search"></span>&nbsp;&nbsp;Consultar
                </button>
            </div>
        </div>
        
    </form>
    
    <p><br /></p>
    
    <?php $horasFaturadasChamadosTotal = '00:00:00'; ?>
    <?php if (($tipoApontamento == 1) || ($tipoApontamento == 2)) { ?>
    <div class="panel-group" id="chamados">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#chamados" href="#collapse1"><b>Chamados</b></a>
                </h4>
            </div>
            <?php 
            if (($tipoApontamento == 1) || ($tipoApontamento == 2)) {
                $in = 'in';
            } else {
                $in = '';
            }
            ?>
            <div id="collapse1" class="panel-collapse collapse <?php echo $in ?> ">
                <div class="panel-body">
                    
                    <?php foreach($chamados AS $registro) { ?>
                    <?php $horasFaturadasChamadosTotal = Functions::sumTimes($horasFaturadasChamadosTotal, Functions::toTime($registro['horasFaturadas']));?>
                        <div class="panel-group" id="accordion">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseCHA<?php echo $registro['chamadoCodigo'] ?>"><?php echo $registro['chamadoCodigo'] . ' - ' . $registro['chamadoAssunto'] ?></a>
                                    </h4>
                                </div>
                                <div id="collapseCHA<?php echo $registro['chamadoCodigo'] ?>" class="panel-collapse collapse">
                                    <div class="panel-body">
                                        <div class="row">
                                            <div class="col-sm-1" style="height:26px;"><b>Código:</b></div>
                                            <div class="col-sm-3" style="height:26px;"><?php echo '<a href="javascript:detalharChamado(' . $registro['chamadoCodigo'] . ');">' . $registro['chamadoCodigo'] . '</a>'?></div>
                                            <div class="col-sm-1" style="height:26px;"><b>Assunto:</b></div>
                                            <div class="col-sm-7" style="height:26px;"><?php echo $registro['chamadoAssunto'] ?></div>
                                        </div>
                                        <div class="row">
                                            <div class="col-sm-1" style="height:26px;"><b>Data:</b></div>
                                            <div class="col-sm-3" style="height:26px;"><?php echo $registro['chamadoData']?></div>
                                            <div class="col-sm-1" style="height:26px;"><b>Situação:</b></div>
                                            <div class="col-sm-3" style="height:26px;"><?php echo $registro['situacaoDescricao']?></div>
                                            <div class="col-sm-1" style="height:26px;"><b>Empresa:</b></div>
                                            <div class="col-sm-3" style="height:26px;"><?php echo $registro['empresaDescricao']?></div>
                                        </div>
                                        <div class="row">
                                            <div class="col-sm-1" style="height:26px;"><b>Cliente:</b></div>
                                            <div class="col-sm-3" style="height:26px;"><?php echo $registro['usuarioNome']?></div>
                                            <div class="col-sm-1" style="height:26px;"><b>Categoria:</b></div>
                                            <div class="col-sm-3" style="height:26px;"><?php echo $registro['categoriaDescricao']?></div>
                                            <div class="col-sm-1" style="height:26px;"><b>Ambiente:</b></div>
                                            <div class="col-sm-3" style="height:26px;"><?php echo $registro['tipoAmbienteDescricao']?></div>
                                        </div>
                                        <div class="row">
                                            <div class="col-sm-1" style="height:26px;"><b>Produto:</b></div>
                                            <div class="col-sm-3" style="height:26px;"><?php echo $registro['tipoProdutoDescricao']?></div>
                                            <div class="col-sm-1" style="height:26px;"><b>Módulo:</b></div>
                                            <div class="col-sm-3" style="height:26px;"><?php echo $registro['moduloDescricao']?></div>
                                            <div class="col-sm-1" style="height:26px;"><b>Faturado:</b></div>
                                            <div class="col-sm-3" style="height:26px;"><?php echo $registro['horasFaturadas']?></div>
                                        </div>
                                        <br />
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th class="col-sm-4">Data</th>
                                                    <th class="col-sm-8">Descrição</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php foreach($registro['chamadoHistoricoArray'] AS $historico) { ?>
                                                <tr>
                                                    <td align="left" colspan="1"><?php echo $historico->getData()?></td>
                                                    <td align="left" colspan="2"><?php echo $historico->getObservacao()?></td>
                                                </tr>
                                                <?php } ?>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                
                </div>
                <div class="panel-footer"><b>Total Chamados: <?php echo $horasFaturadasChamadosTotal?></b></div>
            </div>
        </div>
    </div>
    <?php } ?>
    
    <?php $horasFaturadasAtividadesTotal = '00:00:00'; ?>
    <?php if (($tipoApontamento == 1) || ($tipoApontamento == 3)) { ?>
    <div class="panel-group" id="atividades">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#atividades" href="#collapse2"><b>Atividades</b></a>
                </h4>
            </div>
            <?php 
            if (($tipoApontamento == 1) || ($tipoApontamento == 3)) {
                $in = 'in';
            } else {
                $in = '';
            }
            ?>
            <div id="collapse2" class="panel-collapse collapse <?php echo $in ?> ">
                <div class="panel-body">
                    
                    <?php foreach($atividades AS $registro) { ?>
                    <?php $horasFaturadasAtividadesTotal = Functions::sumTimes($horasFaturadasAtividadesTotal, Functions::toTime($registro['horasFaturadas']));?>
                        <div class="panel-group" id="accordion">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseATI<?php echo $registro['atividadeCodigo'] ?>"><?php echo $registro['atividadeCodigo'] . ' - ' . $registro['atividadeAssunto'] ?></a>
                                    </h4>
                                </div>
                                <div id="collapseATI<?php echo $registro['atividadeCodigo'] ?>" class="panel-collapse collapse">
                                    <div class="panel-body">
                                        <div class="row">
                                            <div class="col-sm-1" style="height:26px;"><b>Código:</b></div>
                                            <div class="col-sm-3" style="height:26px;"><?php echo '<a href="javascript:detalharAtividade(' . $registro['atividadeCodigo'] . ');">' . $registro['atividadeCodigo'] . '</a>'?></div>
                                            <div class="col-sm-1" style="height:26px;"><b>Assunto:</b></div>
                                            <div class="col-sm-7" style="height:26px;"><?php echo $registro['atividadeAssunto'] ?></div>
                                        </div>
                                        <div class="row">
                                            <div class="col-sm-1" style="height:26px;"><b>Data:</b></div>
                                            <div class="col-sm-3" style="height:26px;"><?php echo $registro['atividadeData']?></div>
                                            <div class="col-sm-1" style="height:26px;"><b>Situação:</b></div>
                                            <div class="col-sm-3" style="height:26px;"><?php echo $registro['situacaoDescricao']?></div>
                                            <div class="col-sm-1" style="height:26px;"><b>Empresa:</b></div>
                                            <div class="col-sm-3" style="height:26px;"><?php echo $registro['empresaDescricao']?></div>
                                        </div>
                                        <div class="row">
                                            <div class="col-sm-1" style="height:26px;"><b>Cliente:</b></div>
                                            <div class="col-sm-3" style="height:26px;"><?php echo $registro['usuarioNome']?></div>
                                            <div class="col-sm-1" style="height:26px;"><b>Tipo:</b></div>
                                            <div class="col-sm-3" style="height:26px;"><?php echo $registro['tipoAtividadeDescricao']?></div>
                                            <div class="col-sm-1" style="height:26px;"><b>Faturado:</b></div>
                                            <div class="col-sm-3" style="height:26px;"><?php echo $registro['horasFaturadas']?></div>
                                        </div>
                                        <div class="row">
                                            <div class="col-sm-12"><br /><b>Observações:</b><br /><?php echo $registro['atividadeObservacao']?></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                
                </div>
                <div class="panel-footer"><b>Total Atividades: <?php echo $horasFaturadasAtividadesTotal?></b></div>
            </div>
        </div>
    </div>
    <?php } ?>
    
    <?php
    $horasFaturadasTotal = '00:00:00';
    $horasFaturadasTotal = Functions::sumTimes($horasFaturadasTotal, $horasFaturadasChamadosTotal);
    $horasFaturadasTotal = Functions::sumTimes($horasFaturadasTotal, $horasFaturadasAtividadesTotal);
    ?>
    
    <div class="panel panel-default">
        <div class="panel-body">
        <div class="row">
            <div class="col-sm-12"><b>Total Faturado: <?php echo $horasFaturadasTotal?></b></div>
        </div>
        </div>
    </div>
    
    <button type="button" class="btn btn-default" onclick="javascript:imprimir();">
        <span class="glyphicon glyphicon-print"></span>&nbsp;&nbsp;Imprimir
    </button>
    
</div>

<script type="text/javascript">
    function validar() {
        if (document.filtros.periodoInicial.value == "") {
            alert('Informe algum valor para o campo "Período Inicial"');
            document.filtros.periodoInicial.focus();
            return false;
        }
        if (document.filtros.periodoFinal.value == "") {
            alert('Informe algum valor para o campo "Período Final"');
            document.filtros.periodoFinal.focus();
            return false;
        }
        if (document.filtros.tipoRelatorio.value == "") {
            alert('Informe algum valor para o campo "Tipo de Relatório"');
            document.filtros.tipoRelatorio.focus();
            return false;
        }
        return true;
    }
    function imprimir() {
        postViaJS
        ( ''
        , { controle: 'Chamados'
          , acao: 'relatorioAtendimentos'
          , periodoInicial: document.filtros.periodoInicial.value
          , periodoFinal: document.filtros.periodoFinal.value
          , tipoRelatorio: document.filtros.tipoRelatorio.value
          , tipoApontamento: document.filtros.tipoApontamento.value
          , tipoAvaliacao: document.filtros.tipoAvaliacao.value
          , empresa: document.filtros.empresa.value
          , situacao: document.filtros.situacao.value
          , imprimir: 1
          }
        , "post"
        , "_blank"
        ) ;
    }
    function detalharChamado(chamadoCodigo) {
        postViaJS('', {controle: 'Chamados', acao: 'cadastrar', id: chamadoCodigo}, "post", "_blank");
    }
    function detalharAtividade(atividadeCodigo) {
        postViaJS('', {controle: 'Atividades', acao: 'cadastrar', id: atividadeCodigo}, "post", "_blank");
    }
</script>

<?php include 'pageclose.php';