<?php
    $v_params = $this->getParams();
    
    $mensagem = "";
    if (array_key_exists('mensagem', $v_params)) {
        $mensagem = $v_params['mensagem'];
    }
    
    $periodoInicial = "";
    if (array_key_exists('periodoInicial', $v_params)) {
        $periodoInicial = $v_params['periodoInicial'];
    }
    
    $periodoFinal = "";
    if (array_key_exists('periodoFinal', $v_params)) {
        $periodoFinal = $v_params['periodoFinal'];
    }
    
    $empresa = new EmpresasVo();
    if (array_key_exists('empresa', $v_params)) {
        $empresa = $v_params['empresa'];
    }
    
    $empresas = array();
    if (array_key_exists('empresas', $v_params)) {
        $empresas = $v_params['empresas'];
    }
    
    $registros = array();
    if (array_key_exists('registros', $v_params)) {
        $registros = $v_params['registros'];
    }
?>

<?php include 'pageopen.php' ?>

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script>
    $(document).ready(function() {
        $(".datepicker").datepicker({dateFormat: 'dd/mm/yy'});
    });
</script>

<div class="container">
    
    <div class="page-header">
        <h3>Faturamento por Empresa<small> / Relatório</small></h3>
    </div>
    
    <?php
    if (!empty($mensagem)) {
        if (substr($mensagem,0,1) == "N") {
            echo '<div class="alert alert-danger"><strong>ERRO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
        if (substr($mensagem,0,1) == "S") {
            echo '<div class="alert alert-success"><strong>SUCESSO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
    }
    ?>
    
    <p><br /></p>
    
    <form class="form-horizontal" role="form" method="post">
        
        <input type='hidden' name='controle' value='Apontamentos'>
        <input type='hidden' name='acao' value='relatorioFaturamentoPorEmpresa'>
        
        <div class="form-group">
            <label class="control-label col-sm-1" for="periodoInicial">Início:</label>
            <div class="col-sm-2">
                <input type="text" class="form-control datepicker" id="periodoInicial" name="periodoInicial" value="<?php echo $periodoInicial;?>" />
            </div>
            <label class="control-label col-sm-1" for="periodoFinal">Término:</label>
            <div class="col-sm-2">
                <input type="text" class="form-control datepicker" id="periodoFinal" name="periodoFinal" value="<?php echo $periodoFinal;?>" />
            </div>
            <label class="control-label col-sm-1" for="empresaCodigo">Empresa:</label>
            <div class="col-sm-3">
                <select class="form-control" id="empresaCodigo" name="empresaCodigo">
                    <option value="">Selecione</option>
                    <?php
                    foreach($empresas as $row) {
                        if ($empresa->getId() != "" && $row->getId() == $empresa->getId()) {
                            echo '<option value="' . $row->getId() . '" selected>' . $row->getDescricao() . '</option>';
                        } else {
                            echo '<option value="' . $row->getId() . '">' . $row->getDescricao() . '</option>';
                        }
                    }
                    ?>
                </select>
            </div>
            <div class="col-sm-1">
                <button type="submit" name="submit" value="Consultar" class="btn btn-default">
                    <span class="glyphicon glyphicon-search"></span>&nbsp;&nbsp;Consultar
                </button>
            </div>
        </div>
        
    </form>
    
    <p><br /></p>
    
    <table class="table table-striped">
        
        <thead>
            <tr>
                <th class="col-sm-2">Empresa</th>
                <th class="col-sm-1">Duração</th>
                <th class="col-sm-1">Faturado</th>
                <th class="col-sm-1">Ações</th>
            </tr>
        </thead>
        
        <tbody>
        <?php foreach ($registros AS $registro) { ?>
            <tr>
                <td><?php echo $registro['empresaDescricao']; ?></td>
                <td><?php echo $registro['apontamentoDuracao']; ?></td>
                <td><?php echo $registro['apontamentoFaturado']; ?></td>
                <td>
                    <button type="button" class="btn btn-default btn-xs" onclick="javascript:detalhar(<?php echo $registro['empresaCodigo']?>);">
                        <span class="glyphicon glyphicon-time"></span>&nbsp;Ver Apontamentos
                    </button>
                </td>
            </tr>
        <?php } ?>
        </tbody>
        
    </table>
    
</div>

<script type="text/javascript">
    function detalhar(empresaCodigo) {
        postViaJS('', {controle: 'Apontamentos', acao: 'relatorioApontamentosParaAvaliacao', periodoInicial: document.forms[0].periodoInicial.value, periodoFinal: document.forms[0].periodoFinal.value, empresaCodigo: empresaCodigo, caller: 'relatorioFaturamentoPorEmpresa'}, "post", "_blank");
    }
</script>

<?php include 'pageclose.php';
