<?php
    $v_params = $this->getParams();
    
    $mensagem = "";
    if (array_key_exists('mensagem', $v_params)) {
        $mensagem = $v_params['mensagem'];
    }
    
    $periodoInicial = "";
    if (array_key_exists('periodoInicial', $v_params)) {
        $periodoInicial = $v_params['periodoInicial'];
    }
    
    $periodoFinal = "";
    if (array_key_exists('periodoFinal', $v_params)) {
        $periodoFinal = $v_params['periodoFinal'];
    }
    
    $usuario = new UsuariosVo();
    if (array_key_exists('usuario', $v_params)) {
        $usuario = $v_params['usuario'];
    }
    
    $usuarios = array();
    if (array_key_exists('usuarios', $v_params)) {
        $usuarios = $v_params['usuarios'];
    }
    
    $registros = array();
    if (array_key_exists('registros', $v_params)) {
        $registros = $v_params['registros'];
    }
?>

<?php include 'pageopen.php' ?>

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script>
    $(document).ready(function() {
        $(".datepicker").datepicker({dateFormat: 'dd/mm/yy'});
    });
    function atualizarUsuarioModal() {
        var ajax;
        if (window.XMLHttpRequest)
            ajax = new XMLHttpRequest();
        else
            ajax = new ActiveXObject("Microsoft.XMLHTTP");

        ajax.onreadystatechange = function() {
            if (ajax.readyState == 4 && ajax.status == 200) {
                document.getElementById("usuarioModal").innerHTML = ajax.responseText;
            }
        }
        ajax.open("POST", "?controle=Usuarios&acao=ajaxExibeContatosUsuario", true);
        ajax.setRequestHeader("Content-type","application/x-www-form-urlencoded");
        ajax.send("usuarioCodigo=" + document.getElementById("usuarioCodigo").value);
    }
</script>

<div class="container">
    
    <div class="page-header">
        <h3>Faturamento por Analista<small> / Relatório</small></h3>
    </div>
    
    <?php
    if (!empty($mensagem)) {
        if (substr($mensagem,0,1) == "N") {
            echo '<div class="alert alert-danger"><strong>ERRO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
        if (substr($mensagem,0,1) == "S") {
            echo '<div class="alert alert-success"><strong>SUCESSO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
        }
    }
    ?>
    
    <p><br /></p>
    
    <form class="form-horizontal" role="form" method="post">
        
        <input type='hidden' name='controle' value='Apontamentos'>
        <input type='hidden' name='acao' value='relatorioFaturamentoPorFuncionario'>
        
        <div class="form-group">
            <label class="control-label col-sm-1" for="periodoInicial">Início:</label>
            <div class="col-sm-2">
                <div class="input-group">   
                    <div class="input-group-addon" onclick="document.getElementById('periodoInicial').focus();">
                        <span class="glyphicon glyphicon-calendar"></span> 
                    </div>
                    <input type="text" class="form-control datepicker" id="periodoInicial" name="periodoInicial" value="<?php echo $periodoInicial;?>" />
                </div>
            </div>
            <label class="control-label col-sm-1" for="periodoFinal">Término:</label>
            <div class="col-sm-2">
                <div class="input-group">   
                    <div class="input-group-addon" onclick="document.getElementById('periodoFinal').focus();">
                        <span class="glyphicon glyphicon-calendar"></span> 
                    </div>
                    <input type="text" class="form-control datepicker" id="periodoFinal" name="periodoFinal" value="<?php echo $periodoFinal;?>" />
                </div>
            </div>
            <label class="control-label col-sm-1" for="usuarioCodigo">Analista:</label>
            <div class="col-sm-3">
                <div class="input-group">   
                    <div class="input-group-addon" data-toggle="modal" data-target="#usuarioModal">
                        <span class="glyphicon glyphicon-info-sign"></span> 
                    </div>
                    <select class="form-control" id="usuarioCodigo" name="usuarioCodigo" onchange="atualizarUsuarioModal()">
                        <option value="">Selecione</option>
                        <?php
                        foreach($usuarios as $row) {
                            if ($usuario->getId() != "" && $row->getId() == $usuario->getId()) {
                                echo '<option value="' . $row->getId() . '" selected>' . $row->getNome() . '</option>';
                            } else {
                                echo '<option value="' . $row->getId() . '">' . $row->getNome() . '</option>';
                            }
                        }
                        ?>
                    </select>
                    <div id="usuarioModal" class="modal fade" role="dialog">
                        
                    </div>
                </div>
            </div>
            <div class="col-sm-1">
                <button type="submit" name="submit" value="Consultar" class="btn btn-default">
                    <span class="glyphicon glyphicon-search"></span>&nbsp;&nbsp;Consultar
                </button>
            </div>
        </div>
        
    </form>
    
    <p><br /></p>
    
    <table class="table table-striped">
        
        <thead>
            <tr>
                <th class="col-sm-2">Analista</th>
                <th class="col-sm-1">Duração</th>
                <th class="col-sm-1">Faturado</th>
                <th class="col-sm-1">Ações</th>
            </tr>
        </thead>
        
        <tbody>
        
        <?php 
        $totalApontado = '00:00:00';
        $totalFaturado = '00:00:00';
        
        echo '';
        
        foreach ($registros AS $registro) {
            $totalApontado = Functions::sumTimes($totalApontado, Functions::toTime($registro['apontamentoDuracao']));
            $totalFaturado = Functions::sumTimes($totalFaturado, Functions::toTime($registro['apontamentoFaturado']));
            
            echo '<tr>';
            echo '   <td>' . $registro['usuarioNome'] . '</td>';
            echo '   <td>' . $registro['apontamentoDuracao'] . '</td>';
            echo '   <td>' . $registro['apontamentoFaturado'] . '</td>';
            echo '   <td>' ;
            echo '     <button type="button" class="btn btn-default btn-xs" onclick="javascript:detalhar(' . $registro['usuarioCodigo'] . ');">';
            echo '       <span class="glyphicon glyphicon-time"></span>&nbsp;Ver Apontamentos';
            echo '     </button>';
            echo '   </td>';
            echo '</tr>';
        }
        ?>
        
        <tr>
            <td><br /></td>
            <td><?php echo '<b>' . $totalApontado . '</b>' ?></td>
            <td><?php echo '<b>' . $totalFaturado . '</b>' ?></td>
            <td><br /></td>
        </tr>
        
        </tbody>
        
    </table>
    
</div>

<script type="text/javascript">
    function detalhar(usuarioCodigo) {
        postViaJS('', {controle: 'Apontamentos', acao: 'relatorioApontamentosParaAvaliacao', periodoInicial: document.forms[0].periodoInicial.value, periodoFinal: document.forms[0].periodoFinal.value, usuarioCodigo: usuarioCodigo, caller: 'relatorioFaturamentoPorFuncionario'}, "post", "_blank");
    }
    atualizarUsuarioModal();
</script>

<?php include 'pageclose.php';			
