<?php
    
    $v_params = $this->getParams();
    
    $mensagem = array();
    if (array_key_exists('mensagem', $v_params)) {
        $mensagem = $v_params['mensagem'];
    }
    
    $periodoInicial = array();
    if (array_key_exists('periodoInicial', $v_params)) {
        $periodoInicial = $v_params['periodoInicial'];
    }
    
    $periodoFinal = array();
    if (array_key_exists('periodoFinal', $v_params)) {
        $periodoFinal = $v_params['periodoFinal'];
    }
    
    $tiposRelatorios = array();
    if (array_key_exists('tiposRelatorios', $v_params)) {
        $tiposRelatorios = $v_params['tiposRelatorios'];
    }
    
    $tipoRelatorio = "";
    if (array_key_exists('tipoRelatorio', $v_params)) {
        $tipoRelatorio = $v_params['tipoRelatorio'];
    }
    
    $exibeEmpresaAberta = 0;
    if (array_key_exists('exibeEmpresaAberta', $v_params)) {
        $exibeEmpresaAberta = $v_params['exibeEmpresaAberta'];
    }
    
    $empresas = array();
    if (array_key_exists('empresas', $v_params)) {
        $empresas = $v_params['empresas'];
    }
    
    $empresa = "";
    if (array_key_exists('empresa', $v_params)) {
        $empresa = $v_params['empresa'];
    }
    
    $situacoes = array();
    if (array_key_exists('situacoes', $v_params)) {
        $situacoes = $v_params['situacoes'];
    }
    
    $situacao = "";
    if (array_key_exists('situacao', $v_params)) {
        $situacao = $v_params['situacao'];
    }
    
    $tiposApontamentos = array();
    if (array_key_exists('tiposApontamentos', $v_params)) {
        $tiposApontamentos = $v_params['tiposApontamentos'];
    }
    
    $tipoApontamento = "";
    if (array_key_exists('tipoApontamento', $v_params)) {
        $tipoApontamento = $v_params['tipoApontamento'];
    }
    
    $exibeTipoAvaliacaoAberta = 0;
    if (array_key_exists('exibeTipoAvaliacaoAberta', $v_params)) {
        $exibeTipoAvaliacaoAberta = $v_params['exibeTipoAvaliacaoAberta'];
    }
    
    $tiposAvaliacoes = array();
    if (array_key_exists('tiposAvaliacoes', $v_params)) {
        $tiposAvaliacoes = $v_params['tiposAvaliacoes'];
    }
    
    $tipoAvaliacao = "";
    if (array_key_exists('tipoAvaliacao', $v_params)) {
        $tipoAvaliacao = $v_params['tipoAvaliacao'];
    }
    
    $chamados = array();
    if (array_key_exists('chamados', $v_params)) {
        $chamados = $v_params['chamados'];
    }
    
    $atividades = array();
    if (array_key_exists('atividades', $v_params)) {
        $atividades = $v_params['atividades'];
    }
    
    $horasFaturadasTotal = '00:00:00';
    
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="shortcut icon" href="template/images/favicon.ico">
    
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>BasisIT</title>
</head>

<body>
    <table align="center" border="1" cellspacing="1" cellpadding="1" width="100%">
        <tr>
            <td align="left"><img src="template/images/logo.jpg"></td>
            <td align="center"><b><?php echo "Relatório de Atendimentos - Sintético" ?></b></td>
            <td align="right"><?php echo "Impresso em: " . date("d/m/Y") ?></td>
        </tr>
        <?php if (!Functions::isEmpty($mensagem)) { ?>
        <tr>
            <td align="left" colspan="3">
                <?php
                if (!Functions::isEmpty($mensagem)) {
                    if (substr($mensagem,0,1) == "N") {
                        echo '<div class="alert alert-danger"><strong>ERRO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
                    }
                    if (substr($mensagem,0,1) == "S") {
                        echo '<div class="alert alert-success"><strong>SUCESSO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div>';
                    }
                } else {
                    echo '<br />';
                }
                ?>
            </td>
        </tr>
        <?php } ?>
        <tr>
            <td align="left" colspan="3">
                <?php $horasFaturadasChamadosTotal = '00:00:00'; ?>
                <?php if (($tipoApontamento == 1) || ($tipoApontamento == 2)) { ?>
                <br />
                <table align="center" border="1" cellspacing="1" cellpadding="1" width="100%">
                    <tr>
                        <th align="center" colspan="5"><b>Chamados</b></th>
                    </tr>
                    <tr>
                        <th align="right" width="10%">Código</th>
                        <th align="left" width="20%">Empresa</th>
                        <th align="left" width="20%">Situação</th>
                        <th align="left" width="40%">Assunto</th>
                        <th align="center" width="10%">Horas Faturadas</th>
                    </tr>
                    <?php foreach($chamados AS $registro) { ?>
                    <?php $horasFaturadasChamadosTotal = Functions::sumTimes($horasFaturadasChamadosTotal, Functions::toTime($registro['horasFaturadas']));?>
                    <tr>
                        <td align="right"><?php echo $registro['chamadoCodigo']?></td>
                        <td align="left"><?php echo $registro['empresaDescricao']?></td>
                        <td align="left"><?php echo $registro['situacaoDescricao']?></td>
                        <td align="left"><?php echo $registro['chamadoAssunto']?></td>
                        <td align="center"><?php echo $registro['horasFaturadas']?></td>
                    </tr>
                    <?php } ?>
                    <tr>
                        <th align="right" colspan="4">Total Chamados:</th>
                        <th align="center"><?php echo $horasFaturadasChamadosTotal;?></th>
                    </tr>
                </table>
                <?php } ?>
                
                <?php $horasFaturadasAtividadesTotal = '00:00:00'; ?>
                <?php if (($tipoApontamento == 1) || ($tipoApontamento == 3)) { ?>
                <br />
                <table align="center" border="1" cellspacing="1" cellpadding="1" width="100%">
                    <tr>
                        <th align="center" colspan="5"><b>Atividades</b></th>
                    </tr>
                    <tr>
                        <th align="right" width="10%">Código</th>
                        <th align="left" width="20%">Empresa</th>
                        <th align="left" width="20%">Situação</th>
                        <th align="left" width="40%">Assunto</th>
                        <th align="center" width="10%">Horas Faturadas</th>
                    </tr>
                    <?php foreach($atividades AS $registro) { ?>
                    <?php $horasFaturadasAtividadesTotal = Functions::sumTimes($horasFaturadasAtividadesTotal, Functions::toTime($registro['horasFaturadas']));?>
                    <tr>
                        <td align="right"><?php echo $registro['atividadeCodigo']?></td>
                        <td align="left"><?php echo $registro['empresaDescricao']?></td>
                        <td align="left"><?php echo $registro['situacaoDescricao']?></td>
                        <td align="left"><?php echo $registro['atividadeAssunto']?></td>
                        <td align="center"><?php echo $registro['horasFaturadas']?></td>
                    </tr>
                    <?php } ?>
                    <tr>
                        <th align="right" colspan="4">Total Atividades:</th>
                        <th align="center"><?php echo $horasFaturadasAtividadesTotal;?></th>
                    </tr>
                </table>
                <?php } ?>
                
                <?php
                $horasFaturadasTotal = '00:00:00';
                $horasFaturadasTotal = Functions::sumTimes($horasFaturadasTotal, $horasFaturadasChamadosTotal);
                $horasFaturadasTotal = Functions::sumTimes($horasFaturadasTotal, $horasFaturadasAtividadesTotal);
                ?>
                <br />
                <table align="center" border="1" cellspacing="1" cellpadding="1" width="100%">
                    <tr>
                        <td align="center" colspan="99"><b>Total Faturado: <?php echo $horasFaturadasTotal;?></b></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <script>
        window.print();
    </script>
</body>
</html>