<?php
    
    $v_params = $this->getParams();
    
    $mensagem = array();
    if (array_key_exists('mensagem', $v_params)) {
        $mensagem = $v_params['mensagem'];
    }
    
    $periodoInicial = array();
    if (array_key_exists('periodoInicial', $v_params)) {
        $periodoInicial = $v_params['periodoInicial'];
    }
    
    $periodoFinal = array();
    if (array_key_exists('periodoFinal', $v_params)) {
        $periodoFinal = $v_params['periodoFinal'];
    }
    
    $tiposRelatorios = array();
    if (array_key_exists('tiposRelatorios', $v_params)) {
        $tiposRelatorios = $v_params['tiposRelatorios'];
    }
    
    $tipoRelatorio = "";
    if (array_key_exists('tipoRelatorio', $v_params)) {
        $tipoRelatorio = $v_params['tipoRelatorio'];
    }
    
    $exibeEmpresaAberta = 0;
    if (array_key_exists('exibeEmpresaAberta', $v_params)) {
        $exibeEmpresaAberta = $v_params['exibeEmpresaAberta'];
    }
    
    $empresas = array();
    if (array_key_exists('empresas', $v_params)) {
        $empresas = $v_params['empresas'];
    }
    
    $empresa = "";
    if (array_key_exists('empresa', $v_params)) {
        $empresa = $v_params['empresa'];
    }
    
    $situacoes = array();
    if (array_key_exists('situacoes', $v_params)) {
        $situacoes = $v_params['situacoes'];
    }
    
    $situacao = "";
    if (array_key_exists('situacao', $v_params)) {
        $situacao = $v_params['situacao'];
    }
    
    $tiposApontamentos = array();
    if (array_key_exists('tiposApontamentos', $v_params)) {
        $tiposApontamentos = $v_params['tiposApontamentos'];
    }
    
    $tipoApontamento = "";
    if (array_key_exists('tipoApontamento', $v_params)) {
        $tipoApontamento = $v_params['tipoApontamento'];
    }
    
    $chamados = array();
    if (array_key_exists('chamados', $v_params)) {
        $chamados = $v_params['chamados'];
    }
    
    $atividades = array();
    if (array_key_exists('atividades', $v_params)) {
        $atividades = $v_params['atividades'];
    }
    
    $horasFaturadasTotal = '00:00:00';
    
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="shortcut icon" href="template/images/favicon.ico">
    
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>BasisIT</title>
</head>

<body>
    <table align="center" border="1" cellspacing="1" cellpadding="1" width="100%">
        <tr>
            <td align="left"><img src="template/images/logo.jpg"></td>
            <td align="center"><b><?php echo "Relatório de Atendimentos - Analítico" ?></b></td>
            <td align="right"><?php echo "Impresso em: " . date("d/m/Y") ?></td>
        </tr>
        <?php
        if (!Functions::isEmpty($mensagem)) {
            if (substr($mensagem,0,1) == "N") {
                echo '<tr><td align="left" colspan="3"><div class="alert alert-danger"><strong>ERRO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div></td></tr>';
            }
            if (substr($mensagem,0,1) == "S") {
                echo '<tr><td align="left" colspan="3"><div class="alert alert-success"><strong>SUCESSO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div></td></tr>';
            }
        }
        ?>
        <tr>
            <td align="center" colspan="3"><br /></td>
        </tr>
        <tr>
            <td align="center" colspan="3"><b>Chamados</b></td>
        </tr>
        <tr>
            <td align="left" colspan="3">
                <?php $horasFaturadasChamadosTotal = '00:00:00'; ?>
                <?php foreach($chamados AS $registro) { ?>
                <?php $horasFaturadasChamadosTotal = Functions::sumTimes($horasFaturadasChamadosTotal, Functions::toTime($registro['horasFaturadas']));?>
                <table align="center" border="1" cellspacing="1" cellpadding="1" width="100%">
                    <tr>
                        <td align="left" colspan="4" bgcolor="#DEDEDE"><b><?php echo 'Chamado: ' . $registro['chamadoCodigo'] . ' - ' . $registro['chamadoAssunto']?></b></td>
                    </tr>
                    <tr>
                        <td align="left" colspan="2" width="50%"><b>Data: </b><?php echo $registro['chamadoData']?></td>
                        <td align="left" colspan="2" width="50%"><b>Situação: </b><?php echo $registro['situacaoDescricao']?></td>
                    </tr>
                    <tr>
                        <td align="left" colspan="2"><b>Empresa: </b><?php echo $registro['empresaDescricao']?></td>
                        <td align="left" colspan="2"><b>Cliente: </b><?php echo $registro['usuarioNome']?></td>
                    </tr>
                    <tr>
                        <td align="left" colspan="2"><b>Categoria: </b><?php echo $registro['categoriaDescricao']?></td>
                        <td align="left" colspan="2"><b>Ambiente: </b><?php echo $registro['tipoAmbienteDescricao']?></td>
                    </tr>
                    <tr>
                        <td align="left" colspan="2"><b>Produto: </b><?php echo $registro['tipoProdutoDescricao']?></td>
                        <td align="left" colspan="2"><b>Módulo: </b><?php echo $registro['moduloDescricao']?></td>
                    </tr>
                    <tr>
                        <td align="left" colspan="2"><br /></td>
                        <td align="left" colspan="2"><b>Horas Faturadas: </b><?php echo $registro['horasFaturadas']?></td>
                    </tr>
                </table>
                <table align="center" border="1" cellspacing="1" cellpadding="1" width="100%">    
                    <tr>
                        <th align="left" width="150px">Data</th>
                        <th align="left" colspan="3">Descrição</th>
                    </tr>
                    <?php foreach($registro['chamadoHistoricoArray'] AS $historico) { ?>
                    <tr>
                        <td align="left" width="130px"><?php echo $historico->getData()?></td>
                        <td align="left" colspan="3"><?php echo $historico->getObservacao()?></td>
                    </tr>
                    <?php } ?>
                </table>
                <br />
                <?php } ?>
            </td>
        </tr>
        <tr>
            <td align="left" colspan="2"><b>Total Chamados: </b></td>
            <td align="right"><b><?php echo $horasFaturadasChamadosTotal?></b></td>
        </tr>
        <tr>
            <td align="center" colspan="3"><br /></td>
        </tr>
        <tr>
            <td align="center" colspan="3"><b>Atividades</b></td>
        </tr>
        <tr>
            <td align="left" colspan="3">
            <?php $horasFaturadasAtividadesTotal = '00:00:00'; ?>
            <?php foreach($atividades AS $registro) { ?>
            <?php $horasFaturadasAtividadesTotal = Functions::sumTimes($horasFaturadasAtividadesTotal, Functions::toTime($registro['horasFaturadas']));?>
            <table align="center" border="1" cellspacing="1" cellpadding="1" width="100%">
                <tr>
                    <td align="left" colspan="4" bgcolor="#DEDEDE"><b><?php echo 'Atividade: ' . $registro['atividadeCodigo'] . ' - ' . $registro['atividadeAssunto']?></b></td>
                </tr>
                <tr>
                    <td align="left" colspan="2" width="50%"><b>Data: </b><?php echo $registro['atividadeData']?></td>
                    <td align="left" colspan="2" width="50%"><b>Situação: </b><?php echo $registro['situacaoDescricao']?></td>
                </tr>
                <tr>
                    <td align="left" colspan="2"><b>Empresa: </b><?php echo $registro['empresaDescricao']?></td>
                    <td align="left" colspan="2"><b>Cliente: </b><?php echo $registro['usuarioNome']?></td>
                </tr>
                <tr>
                    <td align="left" colspan="2"><b>Tipo: </b><?php echo $registro['tipoAtividadeDescricao']?></td>
                    <td align="left" colspan="2"><b>Horas Faturadas: </b><?php echo $registro['horasFaturadas']?></td>
                </tr>
                <tr>
                    <td align="left" colspan="4"><b>Observações: </b><br /><?php echo $registro['atividadeObservacao']?></td>
                </tr>
            </table>
            <br />
            <?php } ?>
            </td>
        </tr>
        <tr>
            <td align="left" colspan="2"><b>Total Atividades: </b></td>
            <td align="right"><b><?php echo $horasFaturadasAtividadesTotal?></b></td>
        </tr>
        <?php
        $horasFaturadasTotal = '00:00:00';
        $horasFaturadasTotal = Functions::sumTimes($horasFaturadasTotal, $horasFaturadasChamadosTotal);
        $horasFaturadasTotal = Functions::sumTimes($horasFaturadasTotal, $horasFaturadasAtividadesTotal);
        ?>
        <tr>
            <td align="left" colspan="2"><b>Total Faturado:</b></td>
            <td align="right"><b><?php echo $horasFaturadasTotal;?></b></td>
        </tr>
    </table>
    
    <script>
        window.print();
    </script>
</body>
</html>