<?php
    $v_params = $this->getParams();
    
    $mensagem = array();
    if (array_key_exists('mensagem', $v_params)) {
        $mensagem = $v_params['mensagem'];
    }
    
    $periodoInicial = array();
    if (array_key_exists('periodoInicial', $v_params)) {
        $periodoInicial = $v_params['periodoInicial'];
    }
    
    $periodoFinal = array();
    if (array_key_exists('periodoFinal', $v_params)) {
        $periodoFinal = $v_params['periodoFinal'];
    }
    
    $tiposRelatorios = array();
    if (array_key_exists('tiposRelatorios', $v_params)) {
        $tiposRelatorios = $v_params['tiposRelatorios'];
    }
    
    $tipoRelatorio = "";
    if (array_key_exists('tipoRelatorio', $v_params)) {
        $tipoRelatorio = $v_params['tipoRelatorio'];
    }
    
    $exibeEmpresaAberta = 0;
    if (array_key_exists('exibeEmpresaAberta', $v_params)) {
        $exibeEmpresaAberta = $v_params['exibeEmpresaAberta'];
    }
    
    $empresas = array();
    if (array_key_exists('empresas', $v_params)) {
        $empresas = $v_params['empresas'];
    }
    
    $empresa = "";
    if (array_key_exists('empresa', $v_params)) {
        $empresa = $v_params['empresa'];
    }
    
    $situacoes = array();
    if (array_key_exists('situacoes', $v_params)) {
        $situacoes = $v_params['situacoes'];
    }
    
    $situacao = "";
    if (array_key_exists('situacao', $v_params)) {
        $situacao = $v_params['situacao'];
    }
    
    $tiposApontamentos = array();
    if (array_key_exists('tiposApontamentos', $v_params)) {
        $tiposApontamentos = $v_params['tiposApontamentos'];
    }
    
    $tipoApontamento = "";
    if (array_key_exists('tipoApontamento', $v_params)) {
        $tipoApontamento = $v_params['tipoApontamento'];
    }
    
    $exibeTipoAvaliacaoAberta = 0;
    if (array_key_exists('exibeTipoAvaliacaoAberta', $v_params)) {
        $exibeTipoAvaliacaoAberta = $v_params['exibeTipoAvaliacaoAberta'];
    }
    
    $tiposAvaliacoes = array();
    if (array_key_exists('tiposAvaliacoes', $v_params)) {
        $tiposAvaliacoes = $v_params['tiposAvaliacoes'];
    }
    
    $tipoAvaliacao = "";
    if (array_key_exists('tipoAvaliacao', $v_params)) {
        $tipoAvaliacao = $v_params['tipoAvaliacao'];
    }
    
    $chamados = array();
    if (array_key_exists('chamados', $v_params)) {
        $chamados = $v_params['chamados'];
    }
    
    $atividades = array();
    if (array_key_exists('atividades', $v_params)) {
        $atividades = $v_params['atividades'];
    }
    
    $horasFaturadasChamadosTotal = '00:00:00';
    $horasFaturadasAtividadesTotal = '00:00:00';
    $horasFaturadasTotal = '00:00:00';
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="shortcut icon" href="template/images/favicon.ico">
    
    <title>BasisIT</title>
    
    <style type="text/css">
        * {
          font-family: Calibri;
          font-size: 10px;
          margin: 0; 
          padding: 0px;
        }
        sub {
          font-family: Calibri;
          font-size: 8px;
        }
        h1 {
          font-size: 12px;
          font-family: Calibri;
          font-weight: bold;
        }
        #grid {
          border-collapse: separate;
          border: 0px solid #000000;
          border-spacing: 0;
          font-size: 11pt;
          width: 100%;
          border-color: #000000;
          border-right: 1px solid;
        }
        #grid tr {
          border-color: #000000;
          border-style: none;
          border-width: 0;
        }
        #grid td {
          border-color: #000000;
          border-bottom: 1px solid;
          border-left: 1px solid;
          padding: 2px;
        }
        #grid th {
          border-color: #000000;
          border-top: 1px solid;
          border-bottom: 1px solid;
          border-left: 1px solid;
          background-color: #CCC;
          padding: 2px;
        }
        @media print {
            body {-webkit-print-color-adjust: exact;}
        }
    </style>
</head>

<body>
    <table align="center" width="100%">
        <tr>
            <td width="20%" align="left"><img src="template/images/logo.jpg" width="50%"></td>
            <td width="60%" align="center"><h1>Relatório de Atendimentos<br />Sintético</h1></td>
            <td width="20%" align="right"><sub><?php echo "Impresso em: " . date("d/m/Y") ?></sub></td>
        </tr>
        
        <?php
        if (!Functions::isEmpty($mensagem)) {
            if (substr($mensagem,0,1) == "N") {
                echo '<tr><td align="left" colspan="3"><div class="alert alert-danger"><strong>ERRO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div></td></tr>';
            }
            if (substr($mensagem,0,1) == "S") {
                echo '<tr><td align="left" colspan="3"><div class="alert alert-success"><strong>SUCESSO!</strong>&nbsp;&nbsp;&nbsp;' . substr($mensagem,1,999) . '</div></td></tr>';
            }
        }
        ?>
        
        <tr>
            <td align="center" colspan="3">
                
                <?php if (($tipoApontamento == 1) || ($tipoApontamento == 2)) { ?>
                <p align="center"><b>Chamados</b></p><br />
                
                <table id="grid" align="center" width="100%">
                    <tr>
                        <th align="center" width="40px">Código</th>
                        <th align="center" width="75px">Empresa</th>
                        <th align="center" width="60px">Situação</th>
                        <th align="left">Assunto</th>
                        <th align="center" width="60px">Faturado</th>
                    </tr>
                    <?php foreach($chamados AS $registro) {
                        $horasFaturadasChamadosTotal = Functions::sumTimes($horasFaturadasChamadosTotal, Functions::toTime($registro['horasFaturadas'])); ?>
                        <tr>
                            <td align="center"><?php echo $registro['chamadoCodigo']?></td>
                            <td align="center"><?php echo $registro['empresaDescricao']?></td>
                            <td align="center"><?php echo $registro['situacaoDescricao']?></td>
                            <td align="left"><?php echo $registro['chamadoAssunto']?></td>
                            <td align="center"><?php echo $registro['horasFaturadas']?></td>
                        </tr>
                    <?php } ?>
                    <tr>
                        <td align="right" colspan="4"><br /></td>
                        <td align="center"><?php echo $horasFaturadasChamadosTotal;?></td>
                    </tr>
                </table>
                
                <br />
                <?php } ?>
                
                <?php if (($tipoApontamento == 1) || ($tipoApontamento == 3)) { ?>
                <p align="center"><b>Atividades</b></p><br />
                
                <table id="grid" align="center" width="100%">
                    <tr>
                        <th align="center" width="40px">Código</th>
                        <th align="center" width="75px">Empresa</th>
                        <th align="center" width="60px">Situação</th>
                        <th align="left">Assunto</th>
                        <th align="center" width="60px">Faturado</th>
                    </tr>
                    <?php foreach($atividades AS $registro) {
                        $horasFaturadasAtividadesTotal = Functions::sumTimes($horasFaturadasAtividadesTotal, Functions::toTime($registro['horasFaturadas'])); ?>
                        <tr>
                            <td align="center"><?php echo $registro['atividadeCodigo']?></td>
                            <td align="center"><?php echo $registro['empresaDescricao']?></td>
                            <td align="center"><?php echo $registro['situacaoDescricao']?></td>
                            <td align="left"><?php echo $registro['atividadeAssunto']?></td>
                            <td align="center"><?php echo $registro['horasFaturadas']?></td>
                        </tr>
                    <?php } ?>
                    <tr>
                        <td align="right" colspan="4"><br /></td>
                        <td align="center"><?php echo $horasFaturadasAtividadesTotal;?></td>
                    </tr>
                </table>
                
                <br />
                <?php } ?>
                
                <?php
                $horasFaturadasTotal = Functions::sumTimes($horasFaturadasTotal, $horasFaturadasChamadosTotal);
                $horasFaturadasTotal = Functions::sumTimes($horasFaturadasTotal, $horasFaturadasAtividadesTotal);
                ?>
                <table id="grid" align="center" width="100%">
                    <tr>
                        <th align="left" colspan="4">Total Faturado</th>
                        <th align="center" width="60px"><?php echo $horasFaturadasTotal;?></th>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    
    <script>
        window.print();
    </script>
</body>
</html>