<?php
    $v_params  = $this->getParams();
    
    $registros = array();
    if (array_key_exists('registros', $v_params)) {
        $registros = $v_params['registros'];
    }
    
    $naoClassificados = 0;
    if (array_key_exists('naoClassificados', $v_params)) {
        $naoClassificados = $v_params['naoClassificados'];
    }
    
    $meusRegistros = array();
    if (array_key_exists('meusRegistros', $v_params)) {
        $meusRegistros = $v_params['meusRegistros'];
    }
    
    $resumoGeral = array();
    if (array_key_exists('resumoGeral', $v_params)) {
        $resumoGeral = $v_params['resumoGeral'];
    }
    
    $apontamentosAbertos = array();
    if (array_key_exists('apontamentosAbertos', $v_params)) {
        $apontamentosAbertos = $v_params['apontamentosAbertos'];
    }
    
    $totalMeusRegistrosAtividades = 0;
    $totalMeusRegistrosChamados = 0;
    foreach($meusRegistros AS $meuRegistro) {
        $totalMeusRegistrosAtividades = $totalMeusRegistrosAtividades + $meuRegistro['situacaoQuantidadeAtividades'];
        $totalMeusRegistrosChamados = $totalMeusRegistrosChamados + $meuRegistro['situacaoQuantidadeChamados'];
    }
    
    $totalResumoGeralAtividades = 0;
    $totalResumoGeralChamados = 0;
    foreach($resumoGeral AS $resumo) {
        $totalResumoGeralAtividades = $totalResumoGeralAtividades + $resumo['usuarioQuantidadeAtividades'];
        $totalResumoGeralChamados = $totalResumoGeralChamados + $resumo['usuarioQuantidadeChamados'];
    }
?>

<?php include 'pageopen.php' ?>

<div class="container">
    
    <div class="page-header">
        <h3>Funcionalidades<small> / Tela de Listagem</small></h3>
    </div>
    
    <?php if ($_SESSION['perfilCliente'] == 1) { ?>
        <table width="100%">
            <tr>
                <td align="center" valign="top" style="padding: 5px 5px 5px 5px">
                    
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            <table width="100%">
                                <tr>
                                    <td align="left"><h1><span class="glyphicon glyphicon-tasks"></h1></td>
                                    <td align="right"><b><h2><?php echo '<a href="javascript:;" style="color: #006600" onclick="meusRegistrosChamadosPerfilClienteTotal(' . $_SESSION['usuarioCodigo'] . ');">' . $totalMeusRegistrosChamados . '</a>' ?></h2>Meus Registros</b></td>
                                </tr>
                            </table>
                        </div>
                        <div class="panel-body">
                        <table class="table table-striped">

                            <thead>
                                <tr>
                                    <th class="col-sm-1 text-center">Situação</th>
                                    <th class="col-sm-1 text-center">Chamados</th>
                                </tr>
                            </thead>

                            <tbody>
                                <?php foreach($meusRegistros AS $meuRegistro) { ?>
                                <tr>
                                    <td class="text-center"><?php echo $meuRegistro['situacaoDescricao']; ?></td>
                                    <td class="text-center"><?php echo '<a href="javascript:;" onclick="meusRegistrosChamadosPerfilCliente(' . $_SESSION['usuarioCodigo'] . ',' . $meuRegistro['situacaoCodigo'] . ');">' . $meuRegistro['situacaoQuantidadeChamados'] . '</a>'; ?></td>
                                </tr>
                                <?php } ?>
                            </tbody>

                        </table>
                        </div>
                    </div>
                    
                </td>
                <td align="center" valign="top" style="padding: 5px 5px 5px 5px">
                    
                    <div class="panel panel-warning">
                        <div class="panel-heading">
                            <table width="100%">
                                <tr>
                                    <td align="left"><h1><span class="glyphicon glyphicon-globe"></h1></td>
                                    <td align="right"><b><h2><?php echo '<a href="javascript:;" style="color: #8B7500" onclick="listarMinhaEmpresaChamadosTotal(' . $_SESSION['empresaCodigo'] . ',' . $_SESSION['situacaoEmAndamento'] . ');">' . $totalResumoGeralChamados . '</a>'; ?></h2>Minha Empresa</b></td>
                                </tr>
                            </table>
                        </div>
                        <div class="panel-body">
                        <table class="table table-striped">

                            <thead>
                                <tr>
                                    <th class="col-sm-1 text-center">Usuário</th>
                                    <th class="col-sm-1 text-center">Chamados</th>
                                </tr>
                            </thead>

                            <tbody>
                                <?php foreach($resumoGeral AS $resumo) { ?>
                                <tr>
                                    <td class="text-center"><?php echo $resumo['usuarioNome']; ?></td>
                                    <td class="text-center"><?php echo '<a href="javascript:;" onclick="listarMinhaEmpresaChamados(' . $_SESSION['empresaCodigo'] . ',' . $resumo['usuarioCodigo'] . ',' . $_SESSION['situacaoEmAndamento'] . ');">' . $resumo['usuarioQuantidadeChamados'] . '</a>'; ?></td>
                                </tr>
                                <?php } ?>
                            </tbody>

                        </table>
                        </div>
                    </div>
                    
                </td>
            </tr>
        </table>
    <?php } else { ?>
        <table width="100%">
            <tr>
                <td align="center" valign="top" style="padding: 5px 5px 5px 5px">
                    
                    <div class="panel panel-danger">
                        <div class="panel-heading">
                            <table width="100%">
                                <tr>
                                    <td align="left"><h1><span class="glyphicon glyphicon-comment"></h1></td>
                                    <td align="right"><b><h2><?php echo '<a href="javascript:;" style="color: #AA0000" onclick="naoClassificadosTotal();">' . $naoClassificados . '</a>' ?></h2>Não Classificados</b></td>
                                </tr>
                            </table>
                        </div>
                        <div class="panel-body">
                            <table class="table table-striped">

                                <thead>
                                    <tr>
                                        <th class="col-sm-1 text-center">Não Classificados</th>
                                        <th class="col-sm-1 text-center">Chamados</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    <tr>
                                        <td class="text-center">Quantidade</td>
                                        <td class="text-center"><?php echo '<a href="javascript:;" onclick="naoClassificados();">' . $naoClassificados . '</a>'; ?></td>
                                    </tr>
                                </tbody>

                            </table>
                        </div>
                    </div>
                    
                </td>
                <td align="center" valign="top" style="padding: 5px 5px 5px 5px">
                    
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            <table width="100%">
                                <tr>
                                    <td align="left"><h1><span class="glyphicon glyphicon-tasks"></h1></td>
                                    <td align="right"><b><h2><?php echo '<a href="javascript:;" style="color: #006600" onclick="meusRegistrosAtividadesTotal(' . $_SESSION['usuarioCodigo'] . ');">' . $totalMeusRegistrosAtividades . '</a>' . ' / ' . '<a href="javascript:;" style="color: #006600" onclick="meusRegistrosChamadosDemaisPerfisTotal(' . $_SESSION['usuarioCodigo'] . ');">' . $totalMeusRegistrosChamados . '</a>' ?></h2>Meus Registros</b></td>
                                </tr>
                            </table>
                        </div>
                        <div class="panel-body">
                        <table class="table table-striped">

                            <thead>
                                <tr>
                                    <th class="col-sm-1 text-center">Situação</th>
                                    <th class="col-sm-1 text-center">Atividades</th>
                                    <th class="col-sm-1 text-center">Chamados</th>
                                </tr>
                            </thead>

                            <tbody>
                                <?php foreach($meusRegistros AS $meuRegistro) { ?>
                                <tr>
                                    <td class="text-center"><?php echo $meuRegistro['situacaoDescricao']; ?></td>
                                    <td class="text-center"><?php echo '<a href="javascript:;" onclick="meusRegistrosAtividades(' . $_SESSION['usuarioCodigo'] . ',' . $meuRegistro['situacaoCodigo'] . ');">' . $meuRegistro['situacaoQuantidadeAtividades'] . '</a>'; ?></td>
                                    <td class="text-center"><?php echo '<a href="javascript:;" onclick="meusRegistrosChamadosDemaisPerfis(' . $_SESSION['usuarioCodigo'] . ',' . $meuRegistro['situacaoCodigo'] . ');">' . $meuRegistro['situacaoQuantidadeChamados'] . '</a>'; ?></td>
                                </tr>
                                <?php } ?>
                                <?php foreach($apontamentosAbertos AS $apontamentoAberto) { ?>
                                <tr>
                                    <td class="text-center">Executando</td>
                                    <td class="text-center"><?php echo '<a href="javascript:;" onclick="meusRegistrosExecutandoAtividades(' . $apontamentoAberto['atividadeCodigo'] . ');">' . $apontamentoAberto['quantidadeAtividades'] . '</a>'; ?></td>
                                    <td class="text-center"><?php echo '<a href="javascript:;" onclick="meusRegistrosExecutandoChamados(' . $apontamentoAberto['chamadoCodigo'] . ');">' . $apontamentoAberto['quantidadeChamados'] . '</a>'; ?></td>
                                </tr>
                                <?php } ?>
                            </tbody>

                        </table>
                        </div>
                    </div>
                    
                </td>
                <td align="center" valign="top" style="padding: 5px 5px 5px 5px">
                    
                    <div class="panel panel-warning">
                        <div class="panel-heading">
                            <table width="100%">
                                <tr>
                                    <td align="left"><h1><span class="glyphicon glyphicon-globe"></h1></td>
                                    <td align="right"><b><h2><?php echo '<a href="javascript:;" style="color: #8B7500" onclick="resumoGeralAtividadesTotal(' . $_SESSION['situacaoEmAndamento'] . ');">' . $totalResumoGeralAtividades . '</a>' . ' / ' . '<a href="javascript:;" style="color: #8B7500" onclick="resumoGeralChamadosTotal(' . $_SESSION['situacaoEmAndamento'] . ');">' . $totalResumoGeralChamados . '</a>' ?></h2>Resumo Geral</b></td>
                                </tr>
                            </table>
                        </div>
                        <div class="panel-body">
                        <table class="table table-striped">

                            <thead>
                                <tr>
                                    <th class="col-sm-1 text-center">Analista</th>
                                    <th class="col-sm-1 text-center">Atividades</th>
                                    <th class="col-sm-1 text-center">Chamados</th>
                                </tr>
                            </thead>

                            <tbody>
                                <?php foreach($resumoGeral AS $resumo) { ?>
                                <tr>
                                    <td class="text-center"><?php echo $resumo['usuarioNome']; ?></td>
                                    <td class="text-center"><?php echo '<a href="javascript:;" onclick="resumoGeralAtividades(' . $resumo['usuarioCodigo'] . ',' . $_SESSION['situacaoEmAndamento'] . ');">' . $resumo['usuarioQuantidadeAtividades'] . '</a>'; ?></td>
                                    <td class="text-center"><?php echo '<a href="javascript:;" onclick="resumoGeralChamados(' . $resumo['usuarioCodigo'] . ',' . $_SESSION['situacaoEmAndamento'] . ');">' . $resumo['usuarioQuantidadeChamados'] . '</a>'; ?></td>
                                </tr>
                                <?php } ?>
                            </tbody>

                        </table>
                        </div>
                    </div>
                    
                </td>
            </tr>
        </table>
    <?php } ?>
    
</div>

<script type="text/javascript">
    function post(controle, acao) {
        postViaJS('', {controle: controle, acao: acao});
    }
    
    // Não Classificados
        // Total
        function naoClassificadosTotal() {
            postViaJS('', {controle: 'Chamados', acao: 'listarNaoClassificados'}, "post", "_blank");
        }
        // Normal
        function naoClassificados() {
            postViaJS('', {controle: 'Chamados', acao: 'listarNaoClassificados'}, "post", "_blank");
        }
    
    // Meus Registros
        // Situacao Executando
            // Atividades
            function meusRegistrosExecutandoAtividades(atividadeCodigo) {
                if (atividadeCodigo != 0) {
                    postViaJS('', {controle: 'Atividades', acao: 'cadastrar', id: atividadeCodigo}, "post", "_blank");
                }
            }
            // Chamados
            function meusRegistrosExecutandoChamados(chamadoCodigo) {
                if (chamadoCodigo != 0) {
                    postViaJS('', {controle: 'Chamados', acao: 'cadastrar', id: chamadoCodigo}, "post", "_blank");
                }
            }
        // Situacoes Outras
            // Atividades
                // Total
                function meusRegistrosAtividadesTotal(usuarioCodigo) {
                    postViaJS('', {controle: 'Atividades', acao: 'listar', usuario: usuarioCodigo}, "post", "_blank");
                }
                // Normal
                function meusRegistrosAtividades(usuarioCodigo, situacaoCodigo) {
                    postViaJS('', {controle: 'Atividades', acao: 'listar', usuario: usuarioCodigo, situacao: situacaoCodigo}, "post", "_blank");
                }
            // Chamados
                // Total
                function meusRegistrosChamadosPerfilClienteTotal(usuarioCodigo) {
                    postViaJS('', {controle: 'Chamados', acao: 'listarMeusRegistrosPerfilCliente', usuarioCodigo: usuarioCodigo}, "post", "_blank");
                }
                function meusRegistrosChamadosDemaisPerfisTotal(usuarioCodigo) {
                    postViaJS('', {controle: 'Chamados', acao: 'listarMeusRegistrosDemaisPerfis', usuarioCodigo: usuarioCodigo}, "post", "_blank");
                }
                // Normal
                function meusRegistrosChamadosPerfilCliente(usuarioCodigo, situacaoCodigo) {
                    postViaJS('', {controle: 'Chamados', acao: 'listarMeusRegistrosPerfilCliente', usuarioCodigo: usuarioCodigo, situacaoCodigo: situacaoCodigo}, "post", "_blank");
                }
                function meusRegistrosChamadosDemaisPerfis(usuarioCodigo, situacaoCodigo) {
                    postViaJS('', {controle: 'Chamados', acao: 'listarMeusRegistrosDemaisPerfis', usuarioCodigo: usuarioCodigo, situacaoCodigo: situacaoCodigo}, "post", "_blank");
                }
        // Resumo Geral
            // Atividades
                // Total
                function resumoGeralAtividadesTotal(situacaoCodigo) {
                    postViaJS('', {controle: 'Atividades', acao: 'listar', situacao: situacaoCodigo}, "post", "_blank");
                }
                // Normal
                function resumoGeralAtividades(usuarioCodigo, situacaoCodigo) {
                    postViaJS('', {controle: 'Atividades', acao: 'listar', usuario: usuarioCodigo, situacao: situacaoCodigo}, "post", "_blank");
                }
            // Chamados
                // Total
                function resumoGeralChamadosTotal(situacaoCodigo) {
                    postViaJS('', {controle: 'Chamados', acao: 'listar', situacao: situacaoCodigo}, "post", "_blank");
                }
                // Normal
                function resumoGeralChamados(usuarioCodigo, situacaoCodigo) {
                    postViaJS('', {controle: 'Chamados', acao: 'listar', atendente: usuarioCodigo, situacao: situacaoCodigo}, "post", "_blank");
                }
        // Minha Empresa
            // Chamados
                // Total
                function listarMinhaEmpresaChamadosTotal(empresaCodigo, situacaoCodigo) {
                    postViaJS('', {controle: 'Chamados', acao: 'listarMinhaEmpresa', empresaCodigo: empresaCodigo, situacaoCodigo: situacaoCodigo}, "post", "_blank");
                }
                // Normal
                function listarMinhaEmpresaChamados(empresaCodigo, usuarioCodigo, situacaoCodigo) {
                    postViaJS('', {controle: 'Chamados', acao: 'listarMinhaEmpresa', empresaCodigo: empresaCodigo, usuarioCodigo: usuarioCodigo, situacaoCodigo: situacaoCodigo}, "post", "_blank");
                }
</script>

<?php include 'pageclose.php';